START TRANSACTION;

CREATE TABLE "ReportIntervals" (
    "Id" integer NOT NULL,
    "Name" text,
    CONSTRAINT "PK_ReportIntervals" PRIMARY KEY ("Id")
);

CREATE TABLE "CompanyDriverTargets" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" bigint NOT NULL,
    "ReportIntervalId" integer NOT NULL,
    "TripsCountTarget" integer NOT NULL,
    "TotalIncomeTarget" integer NOT NULL,
    CONSTRAINT "PK_CompanyDriverTargets" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CompanyDriverTargets_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CompanyDriverTargets_ReportIntervals_ReportIntervalId" FOREIGN KEY ("ReportIntervalId") REFERENCES "ReportIntervals" ("Id") ON DELETE CASCADE
);

INSERT INTO "ReportIntervals" ("Id", "Name")
VALUES (0, 'PREV_DAY');
INSERT INTO "ReportIntervals" ("Id", "Name")
VALUES (1, 'PREV_WEEK');
INSERT INTO "ReportIntervals" ("Id", "Name")
VALUES (2, 'PREV_MONTH');
INSERT INTO "ReportIntervals" ("Id", "Name")
VALUES (3, 'CURRENT_DAY');
INSERT INTO "ReportIntervals" ("Id", "Name")
VALUES (4, 'CURRENT_WEEK');
INSERT INTO "ReportIntervals" ("Id", "Name")
VALUES (5, 'CURRENT_MONTH');

CREATE INDEX "IX_CompanyDriverTargets_CompanyId" ON "CompanyDriverTargets" ("CompanyId");

CREATE INDEX "IX_CompanyDriverTargets_ReportIntervalId" ON "CompanyDriverTargets" ("ReportIntervalId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251018163456_add_driverTargets', '8.0.6');

COMMIT;

GRANT SELECT, INSERT, DELETE, UPDATE ON "ReportIntervals" TO limousine;
GRANT SELECT, INSERT, DELETE, UPDATE ON "CompanyDriverTargets" TO limousine;