START TRANSACTION;

--DROP TABLE "CashTransfers";

ALTER TABLE "Counterparties" ADD "CounterpartyTypeId" integer;

CREATE TABLE "CounterpartyTypes" (
    "Id" integer NOT NULL,
    "Name" text,
    CONSTRAINT "PK_CounterpartyTypes" PRIMARY KEY ("Id")
);

CREATE TABLE "RepairDocumentTypes" (
    "Id" integer NOT NULL,
    "Name" text,
    CONSTRAINT "PK_RepairDocumentTypes" PRIMARY KEY ("Id")
);

CREATE TABLE "RepairOrders" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Date" timestamp with time zone NOT NULL,
    "CompanyId" bigint NOT NULL,
    "Number" text,
    "CarId" bigint NOT NULL,
    "CounterPartyId" bigint NOT NULL,
    "TechnicId" bigint NOT NULL,
    "AccountantId" bigint,
    "OperationsDescription" text,
    "CarOdometer" integer NOT NULL,
    "TotalCost" numeric NOT NULL,
    "IsPaid" boolean NOT NULL,
    "IsAccountsReceivable" boolean NOT NULL,
    "CreatedTime" timestamp with time zone NOT NULL,
    "ModifiedTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_RepairOrders" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RepairOrders_Cars_CarId" FOREIGN KEY ("CarId") REFERENCES "Cars" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RepairOrders_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RepairOrders_Counterparties_CounterPartyId" FOREIGN KEY ("CounterPartyId") REFERENCES "Counterparties" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RepairOrders_Users_AccountantId" FOREIGN KEY ("AccountantId") REFERENCES "Users" ("Id"),
    CONSTRAINT "FK_RepairOrders_Users_TechnicId" FOREIGN KEY ("TechnicId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "RepairDocuments" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "RepairOrderId" bigint NOT NULL,
    "RepairDocumentTypeId" integer NOT NULL,
    "UploadedFileId" uuid NOT NULL,
    CONSTRAINT "PK_RepairDocuments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RepairDocuments_RepairDocumentTypes_RepairDocumentTypeId" FOREIGN KEY ("RepairDocumentTypeId") REFERENCES "RepairDocumentTypes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RepairDocuments_RepairOrders_RepairOrderId" FOREIGN KEY ("RepairOrderId") REFERENCES "RepairOrders" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RepairDocuments_UploadedFiles_UploadedFileId" FOREIGN KEY ("UploadedFileId") REFERENCES "UploadedFiles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "RepairOperationTypes" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "RepairOrderId" bigint NOT NULL,
    "Name" text,
    CONSTRAINT "PK_RepairOperationTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RepairOperationTypes_RepairOrders_RepairOrderId" FOREIGN KEY ("RepairOrderId") REFERENCES "RepairOrders" ("Id") ON DELETE CASCADE
);

CREATE TABLE "RepairParts" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "RepairOrderId" bigint NOT NULL,
    "Name" text,
    "ArticleNumber" text,
    "Quantity" numeric NOT NULL,
    "Cost" numeric NOT NULL,
    CONSTRAINT "PK_RepairParts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RepairParts_RepairOrders_RepairOrderId" FOREIGN KEY ("RepairOrderId") REFERENCES "RepairOrders" ("Id") ON DELETE CASCADE
);

CREATE TABLE "RepairOperations" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "RepairOrderId" bigint NOT NULL,
    "RepairOperationTypeId" bigint NOT NULL,
    "Cost" numeric NOT NULL,
    "Comments" text,
    CONSTRAINT "PK_RepairOperations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RepairOperations_RepairOperationTypes_RepairOperationTypeId" FOREIGN KEY ("RepairOperationTypeId") REFERENCES "RepairOperationTypes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RepairOperations_RepairOrders_RepairOrderId" FOREIGN KEY ("RepairOrderId") REFERENCES "RepairOrders" ("Id") ON DELETE CASCADE
);

INSERT INTO "CounterpartyTypes" ("Id", "Name")
VALUES (1, 'Base counterparty');
INSERT INTO "CounterpartyTypes" ("Id", "Name")
VALUES (2, 'Car service');

INSERT INTO "RepairDocumentTypes" ("Id", "Name")
VALUES (1, 'Other');
INSERT INTO "RepairDocumentTypes" ("Id", "Name")
VALUES (2, 'Car photo');
INSERT INTO "RepairDocumentTypes" ("Id", "Name")
VALUES (3, 'Repair order document');

CREATE INDEX "IX_Counterparties_CounterpartyTypeId" ON "Counterparties" ("CounterpartyTypeId");

CREATE INDEX "IX_RepairDocuments_RepairDocumentTypeId" ON "RepairDocuments" ("RepairDocumentTypeId");

CREATE INDEX "IX_RepairDocuments_RepairOrderId" ON "RepairDocuments" ("RepairOrderId");

CREATE INDEX "IX_RepairDocuments_UploadedFileId" ON "RepairDocuments" ("UploadedFileId");

CREATE INDEX "IX_RepairOperations_RepairOperationTypeId" ON "RepairOperations" ("RepairOperationTypeId");

CREATE INDEX "IX_RepairOperations_RepairOrderId" ON "RepairOperations" ("RepairOrderId");

CREATE INDEX "IX_RepairOperationTypes_RepairOrderId" ON "RepairOperationTypes" ("RepairOrderId");

CREATE INDEX "IX_RepairOrders_AccountantId" ON "RepairOrders" ("AccountantId");

CREATE INDEX "IX_RepairOrders_CarId" ON "RepairOrders" ("CarId");

CREATE INDEX "IX_RepairOrders_CompanyId" ON "RepairOrders" ("CompanyId");

CREATE INDEX "IX_RepairOrders_CounterPartyId" ON "RepairOrders" ("CounterPartyId");

CREATE INDEX "IX_RepairOrders_TechnicId" ON "RepairOrders" ("TechnicId");

CREATE INDEX "IX_RepairParts_RepairOrderId" ON "RepairParts" ("RepairOrderId");

ALTER TABLE "Counterparties" ADD CONSTRAINT "FK_Counterparties_CounterpartyTypes_CounterpartyTypeId" FOREIGN KEY ("CounterpartyTypeId") REFERENCES "CounterpartyTypes" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251120185318_add_repair_orders', '8.0.6');

COMMIT;

START TRANSACTION;

ALTER TABLE "RepairOperationTypes" DROP CONSTRAINT "FK_RepairOperationTypes_RepairOrders_RepairOrderId";

DROP INDEX "IX_RepairOperationTypes_RepairOrderId";

ALTER TABLE "RepairOperationTypes" DROP COLUMN "RepairOrderId";

ALTER TABLE "RepairOrders" ADD "Deleted" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (60, '', 'repair cars / read', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (61, '', 'repair cars / add', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (62, '', 'repair cars / delete', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (63, '', 'repair cars / change', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (64, '', 'repair cars / set paid status', 0);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251122155836_correct_repair_orders', '8.0.6');

COMMIT;

START TRANSACTION;

ALTER TABLE "RepairOrders" ADD "TransactionId" bigint;

INSERT INTO "PurposeReportType" ("Id", "Name")
VALUES (3, 'Repair service');

CREATE INDEX "IX_RepairOrders_TransactionId" ON "RepairOrders" ("TransactionId");

ALTER TABLE "RepairOrders" ADD CONSTRAINT "FK_RepairOrders_Transactions_TransactionId" FOREIGN KEY ("TransactionId") REFERENCES "Transactions" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251204184112_add_repair_transaction_and_purpose_type', '8.0.6');

COMMIT;

START TRANSACTION;

ALTER TABLE "Transactions" ADD "CancelledTime" timestamp with time zone;

ALTER TABLE "Transactions" ADD "CancelledUserId" bigint;

CREATE INDEX "IX_Transactions_CancelledUserId" ON "Transactions" ("CancelledUserId");

ALTER TABLE "Transactions" ADD CONSTRAINT "FK_Transactions_Users_CancelledUserId" FOREIGN KEY ("CancelledUserId") REFERENCES "Users" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251205192904_add_cancelled_transaction_fields', '8.0.6');

COMMIT;

GRANT SELECT, INSERT, DELETE, UPDATE ON "CounterpartyTypes" TO limousine;
GRANT SELECT, INSERT, DELETE, UPDATE ON "RepairDocumentTypes" TO limousine;
GRANT SELECT, INSERT, DELETE, UPDATE ON "RepairOrders" TO limousine;
GRANT SELECT, INSERT, DELETE, UPDATE ON "RepairDocuments" TO limousine;
GRANT SELECT, INSERT, DELETE, UPDATE ON "RepairOperationTypes" TO limousine;
GRANT SELECT, INSERT, DELETE, UPDATE ON "RepairParts" TO limousine;
GRANT SELECT, INSERT, DELETE, UPDATE ON "RepairOperations" TO limousine;

