START TRANSACTION;

ALTER TABLE "CarUsages" ADD "EndTime" timestamp with time zone;

CREATE TABLE "DriverActivityChanges" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" bigint NOT NULL,
    "StartTime" timestamp with time zone NOT NULL,
    "EndTime" timestamp with time zone,
    "DriverActivityStatusId" integer NOT NULL,
    "Details" text,
    CONSTRAINT "PK_DriverActivityChanges" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DriverActivityChanges_DriverActivityStatuses_DriverActivity~" FOREIGN KEY ("DriverActivityStatusId") REFERENCES "DriverActivityStatuses" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_DriverActivityChanges_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "DriverCarChanges" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CarId" bigint NOT NULL,
    "StartTime" timestamp with time zone NOT NULL,
    "EndTime" timestamp with time zone,
    "UserId" bigint NOT NULL,
    "Details" text,
    CONSTRAINT "PK_DriverCarChanges" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DriverCarChanges_Cars_CarId" FOREIGN KEY ("CarId") REFERENCES "Cars" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_DriverCarChanges_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_CarUsages_EndTime" ON "CarUsages" ("EndTime");

CREATE INDEX "IX_DriverActivityChanges_DriverActivityStatusId" ON "DriverActivityChanges" ("DriverActivityStatusId");

CREATE INDEX "IX_DriverActivityChanges_EndTime" ON "DriverActivityChanges" ("EndTime");

CREATE INDEX "IX_DriverActivityChanges_StartTime" ON "DriverActivityChanges" ("StartTime");

CREATE INDEX "IX_DriverActivityChanges_UserId" ON "DriverActivityChanges" ("UserId");

CREATE INDEX "IX_DriverCarChanges_CarId" ON "DriverCarChanges" ("CarId");

CREATE INDEX "IX_DriverCarChanges_EndTime" ON "DriverCarChanges" ("EndTime");

CREATE INDEX "IX_DriverCarChanges_StartTime" ON "DriverCarChanges" ("StartTime");

CREATE INDEX "IX_DriverCarChanges_UserId" ON "DriverCarChanges" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251103132702_add_driver_activity_change_and_car_change', '8.0.6');

COMMIT;

START TRANSACTION;

UPDATE "CarClasses" SET "Name" = 'LEXUS, TESLA, CITROEN, PALISADE'
WHERE "Id" = 1;

UPDATE "CarClasses" SET "Name" = 'GMC, CADILAC'
WHERE "Id" = 2;

INSERT INTO "CarClasses" ("Id", "Name")
VALUES (3, 'VIANO');
INSERT INTO "CarClasses" ("Id", "Name")
VALUES (4, 'HIGHLANDER');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251104070429_add_carclasses', '8.0.6');

COMMIT;

GRANT SELECT, INSERT, DELETE, UPDATE ON "DriverCarChanges" TO limousine;
GRANT SELECT, INSERT, DELETE, UPDATE ON "DriverActivityChanges" TO limousine;