START TRANSACTION;
ALTER TABLE "LogDbItems" DROP CONSTRAINT "FK_LogDbItems_LogDbEntries_LogDbEntryId";

ALTER TABLE "LogDbItems" DROP CONSTRAINT "FK_LogDbItems_Users_UserId";

ALTER TABLE "YoocaOrders" DROP CONSTRAINT "FK_YoocaOrders_LogDbEntries_LogDbEntryId";

DROP INDEX "IX_YoocaOrders_LogDbEntryId";

DROP INDEX "IX_LogDbItems_UserId";

ALTER TABLE "LogDbItems" DROP COLUMN "Time";

ALTER TABLE "LogDbItems" DROP COLUMN "UserId";

ALTER TABLE "LogDbItems" RENAME COLUMN "LogDbEntryId" TO "LogDbActionId";

ALTER TABLE "LogDbItems" RENAME COLUMN "EntityName" TO "OldDisplayValue";

ALTER INDEX "IX_LogDbItems_LogDbEntryId" RENAME TO "IX_LogDbItems_LogDbActionId";

ALTER TABLE "YoocaUsers" ADD "DeviceToken" text;

ALTER TABLE "YoocaOrders" ALTER COLUMN "LogDbEntryId" DROP NOT NULL;

ALTER TABLE "YoocaOrders" ADD "CompanyId" bigint NOT NULL DEFAULT 0;

ALTER TABLE "YoocaLocations" ADD "LogDbEntryId" bigint;

ALTER TABLE "LogDbItems" ADD "LinkedEntityName" text;

ALTER TABLE "LogDbItems" ADD "NewDisplayValue" text;

ALTER TABLE "LogDbEntries" ADD "CompanyId" bigint;

ALTER TABLE "LogDbEntries" ADD "DisplayName" text;

ALTER TABLE "LogDbEntries" ADD "EntityId" text;

ALTER TABLE "LogDbEntries" ADD "EntityName" text;

ALTER TABLE "LogDbEntries" ADD "LogDbParentId" bigint;

CREATE TABLE "LogDbActions" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "LogDbEntryId" bigint NOT NULL,
    "Time" timestamp with time zone NOT NULL,
    "LogDbActionTypeId" integer NOT NULL,
    "UserId" bigint,
    CONSTRAINT "PK_LogDbActions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LogDbActions_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_LogDbActions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
);

INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (81, '', 'yooca cars / set price', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (82, '', 'yooca cars / decline', 0);

INSERT INTO "YoocaOrderStatuses" ("Id", "Name")
VALUES (9, 'Payment failed');

CREATE UNIQUE INDEX "IX_YoocaOrders_LogDbEntryId" ON "YoocaOrders" ("LogDbEntryId");

CREATE INDEX "IX_YoocaLocations_LogDbEntryId" ON "YoocaLocations" ("LogDbEntryId");

CREATE INDEX "IX_LogDbEntries_CompanyId" ON "LogDbEntries" ("CompanyId");

CREATE INDEX "IX_LogDbEntries_EntityName_EntityId" ON "LogDbEntries" ("EntityName", "EntityId");

CREATE INDEX "IX_LogDbEntries_LogDbParentId" ON "LogDbEntries" ("LogDbParentId");

CREATE INDEX "IX_LogDbActions_LogDbEntryId" ON "LogDbActions" ("LogDbEntryId");

CREATE INDEX "IX_LogDbActions_Time" ON "LogDbActions" ("Time");

CREATE INDEX "IX_LogDbActions_UserId" ON "LogDbActions" ("UserId");

ALTER TABLE "LogDbEntries" ADD CONSTRAINT "FK_LogDbEntries_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id");

ALTER TABLE "LogDbEntries" ADD CONSTRAINT "FK_LogDbEntries_LogDbEntries_LogDbParentId" FOREIGN KEY ("LogDbParentId") REFERENCES "LogDbEntries" ("Id");

ALTER TABLE "LogDbItems" ADD CONSTRAINT "FK_LogDbItems_LogDbActions_LogDbActionId" FOREIGN KEY ("LogDbActionId") REFERENCES "LogDbActions" ("Id") ON DELETE CASCADE;

ALTER TABLE "YoocaLocations" ADD CONSTRAINT "FK_YoocaLocations_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id");

ALTER TABLE "YoocaOrders" ADD CONSTRAINT "FK_YoocaOrders_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260228185717_update_logdb', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "CarUploadedFiles" ADD "LogDbEntryId" bigint;

ALTER TABLE "Cars" ADD "LogDbEntryId" bigint;

CREATE INDEX "IX_CarUploadedFiles_LogDbEntryId" ON "CarUploadedFiles" ("LogDbEntryId");

CREATE INDEX "IX_Cars_LogDbEntryId" ON "Cars" ("LogDbEntryId");

ALTER TABLE "Cars" ADD CONSTRAINT "FK_Cars_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id");

ALTER TABLE "CarUploadedFiles" ADD CONSTRAINT "FK_CarUploadedFiles_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260228211644_add_car_logdb', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "Users" ADD "PosTerminalId" bigint;

CREATE TABLE "PosTerminals" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" bigint NOT NULL,
    "Name" text,
    "Description" text,
    "Deleted" boolean NOT NULL,
    CONSTRAINT "PK_PosTerminals" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PosTerminals_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PosTerminalUsages" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "PosTerminalId" bigint NOT NULL,
    "StartTime" timestamp with time zone NOT NULL,
    "EndTime" timestamp with time zone,
    "UserId" bigint,
    CONSTRAINT "PK_PosTerminalUsages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PosTerminalUsages_PosTerminals_PosTerminalId" FOREIGN KEY ("PosTerminalId") REFERENCES "PosTerminals" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PosTerminalUsages_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
);

INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (91, '', 'POS terminal / read', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (92, '', 'POS terminal / add', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (93, '', 'POS terminal / change', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (94, '', 'POS terminal / delete', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (95, '', 'Drivers / change acquiring terminal only', 0);

CREATE INDEX "IX_Users_PosTerminalId" ON "Users" ("PosTerminalId");

CREATE INDEX "IX_PosTerminals_CompanyId" ON "PosTerminals" ("CompanyId");

CREATE INDEX "IX_PosTerminals_Name" ON "PosTerminals" ("Name");

CREATE INDEX "IX_PosTerminalUsages_EndTime" ON "PosTerminalUsages" ("EndTime");

CREATE INDEX "IX_PosTerminalUsages_PosTerminalId" ON "PosTerminalUsages" ("PosTerminalId");

CREATE INDEX "IX_PosTerminalUsages_StartTime" ON "PosTerminalUsages" ("StartTime");

CREATE INDEX "IX_PosTerminalUsages_UserId" ON "PosTerminalUsages" ("UserId");

ALTER TABLE "Users" ADD CONSTRAINT "FK_Users_PosTerminals_PosTerminalId" FOREIGN KEY ("PosTerminalId") REFERENCES "PosTerminals" ("Id") ON DELETE SET NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260304185731_add_PosTerminal', '10.0.1');

COMMIT;

GRANT SELECT, INSERT, DELETE, UPDATE ON "LogDbActions" TO limousine;
GRANT SELECT, INSERT, DELETE, UPDATE ON "PosTerminals" TO limousine;
GRANT SELECT, INSERT, DELETE, UPDATE ON "PosTerminalUsages" TO limousine;