START TRANSACTION;
ALTER TABLE "SalaryDocuments" ADD "MileageOvage" numeric NOT NULL DEFAULT 0.0;

ALTER TABLE "Companies" ADD "MileageOvageDailyNormKm" integer NOT NULL DEFAULT 0;

ALTER TABLE "Companies" ADD "MileageOvageMinRevenueBase" numeric NOT NULL DEFAULT 0.0;

ALTER TABLE "Companies" ADD "MileageOvageRatePerKm" numeric NOT NULL DEFAULT 0.0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260609181140_AddMileageOvageSettings', '10.0.1');

COMMIT;

START TRANSACTION;
CREATE TABLE "AutoWithdrawalSettings" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" bigint NOT NULL,
    "CashBoxId" bigint NOT NULL,
    "Enabled" boolean NOT NULL,
    "DayOfWeek" integer NOT NULL,
    "StartHourUtc" integer NOT NULL,
    "WindowHours" integer NOT NULL,
    "MinBalance" numeric NOT NULL,
    "Deleted" boolean NOT NULL,
    CONSTRAINT "PK_AutoWithdrawalSettings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AutoWithdrawalSettings_CashBoxes_CashBoxId" FOREIGN KEY ("CashBoxId") REFERENCES "CashBoxes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AutoWithdrawalSettings_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE
);

INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (142, '', 'Auto withdrawal / read', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (143, '', 'Auto withdrawal / write', 0);

CREATE INDEX "IX_AutoWithdrawalSettings_CashBoxId" ON "AutoWithdrawalSettings" ("CashBoxId");

CREATE INDEX "IX_AutoWithdrawalSettings_CompanyId" ON "AutoWithdrawalSettings" ("CompanyId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260609192840_AddAutoWithdrawalSettings', '10.0.1');

COMMIT;

START TRANSACTION;
CREATE TABLE "BotManagers" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" bigint NOT NULL,
    "TelegramUserId" bigint,
    "Username" text,
    "Role" integer NOT NULL,
    "ReceivesIgnitionAlerts" boolean NOT NULL,
    "ReceivesTaskMentions" boolean NOT NULL,
    "CanEditKnowledge" boolean NOT NULL,
    "Deleted" boolean NOT NULL,
    "CreatedTime" timestamp with time zone NOT NULL,
    "ModifiedTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_BotManagers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BotManagers_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE
);

CREATE TABLE "CompanyBotConfigs" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" bigint NOT NULL,
    "BotToken" text,
    "TargetGroupChatId" bigint NOT NULL,
    "IsActive" boolean NOT NULL,
    "AssistantName" text,
    "PersonaPrompt" text,
    "EfficiencyTarget" numeric NOT NULL,
    "DailyAiCallBudget" integer NOT NULL,
    "DailyReminderHour" integer NOT NULL,
    "DailyReminderMinute" integer NOT NULL,
    "Deleted" boolean NOT NULL,
    "CreatedTime" timestamp with time zone NOT NULL,
    "ModifiedTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_CompanyBotConfigs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CompanyBotConfigs_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE
);

CREATE TABLE "BotManagerInvites" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" bigint NOT NULL,
    "BotManagerId" bigint NOT NULL,
    "Token" text,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "RedeemedAt" timestamp with time zone,
    "Deleted" boolean NOT NULL,
    "CreatedTime" timestamp with time zone NOT NULL,
    "ModifiedTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_BotManagerInvites" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BotManagerInvites_BotManagers_BotManagerId" FOREIGN KEY ("BotManagerId") REFERENCES "BotManagers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_BotManagerInvites_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_BotManagerInvites_BotManagerId" ON "BotManagerInvites" ("BotManagerId");

CREATE INDEX "IX_BotManagerInvites_CompanyId_RedeemedAt" ON "BotManagerInvites" ("CompanyId", "RedeemedAt");

CREATE UNIQUE INDEX "IX_BotManagerInvites_Token" ON "BotManagerInvites" ("Token");

CREATE INDEX "IX_BotManagers_CompanyId_Role" ON "BotManagers" ("CompanyId", "Role");

CREATE UNIQUE INDEX "IX_BotManagers_CompanyId_TelegramUserId" ON "BotManagers" ("CompanyId", "TelegramUserId") WHERE "TelegramUserId" IS NOT NULL;

CREATE UNIQUE INDEX "IX_CompanyBotConfigs_CompanyId" ON "CompanyBotConfigs" ("CompanyId") WHERE "Deleted" = false;

CREATE INDEX "IX_CompanyBotConfigs_IsActive" ON "CompanyBotConfigs" ("IsActive");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260610165305_AddBotMultiTenantConfig', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "EmbeddingChunks" ADD "Dimension" integer;

ALTER TABLE "EmbeddingChunks" ADD "EmbeddingModel" text;

ALTER TABLE "ChatMessages" ADD "CompanyId" bigint;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260610170339_AddBotSoftScopingColumns', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "CompanyBotConfigs" ADD "BotUsername" text;

INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (144, '', 'Telegram bot config / read', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (145, '', 'Telegram bot config / write', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (146, '', 'Telegram bot managers / read', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (147, '', 'Telegram bot managers / write', 0);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260610185707_AddBotConfigAccessAndUsername', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "DriverCarChanges" ADD "LogDbEntryId" bigint;

ALTER TABLE "DriverActivityChanges" ADD "LogDbEntryId" bigint;

INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (148, '', 'Driver work status & car / read', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (149, '', 'Driver work status & car / change', 0);

CREATE INDEX "IX_DriverCarChanges_LogDbEntryId" ON "DriverCarChanges" ("LogDbEntryId");

CREATE INDEX "IX_DriverActivityChanges_LogDbEntryId" ON "DriverActivityChanges" ("LogDbEntryId");

ALTER TABLE "DriverActivityChanges" ADD CONSTRAINT "FK_DriverActivityChanges_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id");

ALTER TABLE "DriverCarChanges" ADD CONSTRAINT "FK_DriverCarChanges_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id");


                INSERT INTO "DriverActivityChanges" ("UserId", "StartTime", "DriverActivityStatusId", "Details")
                SELECT u."Id", now(), u."DriverActivityStatusId", ''
                FROM "Users" u
                WHERE u."Role" = 0
                  AND NOT EXISTS (SELECT 1 FROM "DriverActivityChanges" a WHERE a."UserId" = u."Id");


                INSERT INTO "DriverCarChanges" ("UserId", "CarId", "StartTime", "Details")
                SELECT u."Id", u."CarId", now(), ''
                FROM "Users" u
                WHERE u."Role" = 0
                  AND u."CarId" IS NOT NULL
                  AND NOT EXISTS (SELECT 1 FROM "DriverCarChanges" c WHERE c."UserId" = u."Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260610200511_AddAuditToDriverActivityAndCarChange', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "Companies" ADD "HideBoltInReports" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Companies" ADD "HideCareemInReports" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Companies" ADD "HideUberInReports" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Companies" ADD "HideYangoInReports" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Companies" ADD "HideZedInReports" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260612124734_AddCompanyAggregatorVisibility', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "Companies" ADD "Address" text;

ALTER TABLE "Companies" ADD "BankName" text;

ALTER TABLE "Companies" ADD "Email" text;

ALTER TABLE "Companies" ADD "IBAN" text;

ALTER TABLE "Companies" ADD "Phone" text;

ALTER TABLE "Companies" ADD "SWIFT" text;

ALTER TABLE "Companies" ADD "TRN" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260612170752_AddCompanyRequisites', '10.0.1');

COMMIT;

START TRANSACTION;
UPDATE "BotManagers" SET "Deleted" = true WHERE "Deleted" = false;

UPDATE "BotManagerInvites" SET "Deleted" = true WHERE "Deleted" = false;

DROP INDEX "IX_BotManagers_CompanyId_Role";

DROP INDEX "IX_BotManagers_CompanyId_TelegramUserId";

ALTER TABLE "BotManagers" DROP COLUMN "CanEditKnowledge";

ALTER TABLE "BotManagers" DROP COLUMN "Role";

ALTER TABLE "BotManagers" DROP COLUMN "Username";

ALTER TABLE "BotManagers" ADD "CrmUserId" bigint NOT NULL DEFAULT 0;

CREATE TABLE "BotAccessAttempts" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" bigint NOT NULL,
    "TelegramUserId" bigint,
    "TelegramUsername" text,
    "TelegramChatId" bigint NOT NULL,
    "Text" text,
    "Reason" integer NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL,
    "Deleted" boolean NOT NULL,
    "CreatedTime" timestamp with time zone NOT NULL,
    "ModifiedTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_BotAccessAttempts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BotAccessAttempts_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE
);

CREATE TABLE "BotConversationMessages" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" bigint NOT NULL,
    "BotManagerId" bigint NOT NULL,
    "Direction" integer NOT NULL,
    "TelegramMessageId" integer,
    "Text" text,
    "Timestamp" timestamp with time zone NOT NULL,
    "Deleted" boolean NOT NULL,
    "CreatedTime" timestamp with time zone NOT NULL,
    "ModifiedTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_BotConversationMessages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BotConversationMessages_BotManagers_BotManagerId" FOREIGN KEY ("BotManagerId") REFERENCES "BotManagers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_BotConversationMessages_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE
);

INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (150, '', 'Telegram bot knowledge / write', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (151, '', 'Telegram bot conversations / read', 0);

CREATE UNIQUE INDEX "IX_BotManagers_CompanyId_CrmUserId" ON "BotManagers" ("CompanyId", "CrmUserId") WHERE "Deleted" = false;

CREATE UNIQUE INDEX "IX_BotManagers_CompanyId_TelegramUserId" ON "BotManagers" ("CompanyId", "TelegramUserId") WHERE "Deleted" = false AND "TelegramUserId" IS NOT NULL;

CREATE INDEX "IX_BotManagers_CrmUserId" ON "BotManagers" ("CrmUserId");

CREATE UNIQUE INDEX "IX_BotManagerInvites_CompanyId_BotManagerId" ON "BotManagerInvites" ("CompanyId", "BotManagerId") WHERE "RedeemedAt" IS NULL AND "Deleted" = false;

CREATE INDEX "IX_BotAccessAttempts_CompanyId_TelegramUserId_Timestamp" ON "BotAccessAttempts" ("CompanyId", "TelegramUserId", "Timestamp");

CREATE INDEX "IX_BotAccessAttempts_CompanyId_Timestamp" ON "BotAccessAttempts" ("CompanyId", "Timestamp");

CREATE INDEX "IX_BotConversationMessages_BotManagerId" ON "BotConversationMessages" ("BotManagerId");

CREATE INDEX "IX_BotConversationMessages_CompanyId_BotManagerId_Timestamp" ON "BotConversationMessages" ("CompanyId", "BotManagerId", "Timestamp");

ALTER TABLE "BotManagers" ADD CONSTRAINT "FK_BotManagers_Users_CrmUserId" FOREIGN KEY ("CrmUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;


                INSERT INTO "CompanyRoleAccesses" ("CompanyId", "UserRoleId", "AuthAccessId", "AccessAllowed")
                SELECT c."Id", 1, 150, true FROM "Companies" c
                WHERE NOT EXISTS (
                    SELECT 1 FROM "CompanyRoleAccesses" cra
                    WHERE cra."CompanyId" = c."Id" AND cra."UserRoleId" = 1 AND cra."AuthAccessId" = 150
                );
                INSERT INTO "CompanyRoleAccesses" ("CompanyId", "UserRoleId", "AuthAccessId", "AccessAllowed")
                SELECT c."Id", 1, 151, true FROM "Companies" c
                WHERE NOT EXISTS (
                    SELECT 1 FROM "CompanyRoleAccesses" cra
                    WHERE cra."CompanyId" = c."Id" AND cra."UserRoleId" = 1 AND cra."AuthAccessId" = 151
                );


INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260613114631_AddBotPortalUserBinding', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "Counterparties" DROP CONSTRAINT "FK_Counterparties_CounterpartyTypes_CounterpartyTypeId";

DELETE FROM "CounterpartyTypes"
WHERE "Id" = 1;

DELETE FROM "CounterpartyTypes"
WHERE "Id" = 2;

ALTER TABLE "CounterpartyTypes" ALTER COLUMN "Id" TYPE bigint;
ALTER TABLE "CounterpartyTypes" ALTER COLUMN "Id" DROP DEFAULT;
ALTER TABLE "CounterpartyTypes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE "CounterpartyTypes" ADD "CompanyId" bigint NOT NULL DEFAULT 0;

ALTER TABLE "CounterpartyTypes" ADD "Deleted" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "CounterpartyTypes" ADD "IsDefault" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "CounterpartyTypes" ADD "IsSystem" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "CounterpartyTypes" ADD "LogDbEntryId" bigint;

ALTER TABLE "CounterpartyTypes" ADD "SystemCode" integer;

ALTER TABLE "Counterparties" ALTER COLUMN "CounterpartyTypeId" TYPE bigint;

ALTER TABLE "Counterparties" ADD "Address" text;

ALTER TABLE "Counterparties" ADD "Archived" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Counterparties" ADD "BankName" text;

ALTER TABLE "Counterparties" ADD "Deleted" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Counterparties" ADD "Email" text;

ALTER TABLE "Counterparties" ADD "IBAN" text;

ALTER TABLE "Counterparties" ADD "LegalName" text;

ALTER TABLE "Counterparties" ADD "Phone" text;

ALTER TABLE "Counterparties" ADD "SWIFT" text;

ALTER TABLE "Counterparties" ADD "TRN" text;

ALTER TABLE "Companies" ADD "DirectorName" text;

CREATE TABLE "CounterpartyContacts" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CounterpartyId" bigint NOT NULL,
    "FullName" text,
    "Position" text,
    "Phone" text,
    "Email" text,
    "Note" text,
    "Deleted" boolean NOT NULL,
    "LogDbEntryId" bigint,
    CONSTRAINT "PK_CounterpartyContacts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CounterpartyContacts_Counterparties_CounterpartyId" FOREIGN KEY ("CounterpartyId") REFERENCES "Counterparties" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CounterpartyContacts_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id")
);

CREATE TABLE "CounterpartyDocuments" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CounterpartyId" bigint NOT NULL,
    "UploadedFileId" uuid NOT NULL,
    "FileName" text,
    "MimeType" text,
    "Size" bigint NOT NULL,
    "DocumentType" integer NOT NULL,
    "UploadedByUserId" bigint NOT NULL,
    "Note" text,
    "Deleted" boolean NOT NULL,
    "LogDbEntryId" bigint,
    CONSTRAINT "PK_CounterpartyDocuments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CounterpartyDocuments_Counterparties_CounterpartyId" FOREIGN KEY ("CounterpartyId") REFERENCES "Counterparties" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CounterpartyDocuments_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id"),
    CONSTRAINT "FK_CounterpartyDocuments_UploadedFiles_UploadedFileId" FOREIGN KEY ("UploadedFileId") REFERENCES "UploadedFiles" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_CounterpartyDocuments_Users_UploadedByUserId" FOREIGN KEY ("UploadedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE UNIQUE INDEX "IX_CounterpartyTypes_CompanyId" ON "CounterpartyTypes" ("CompanyId") WHERE "IsDefault" AND NOT "Deleted";

CREATE UNIQUE INDEX "IX_CounterpartyTypes_CompanyId_Name" ON "CounterpartyTypes" ("CompanyId", "Name") WHERE "Deleted" = false;

CREATE INDEX "IX_CounterpartyTypes_LogDbEntryId" ON "CounterpartyTypes" ("LogDbEntryId");

CREATE INDEX "IX_CounterpartyContacts_CounterpartyId" ON "CounterpartyContacts" ("CounterpartyId");

CREATE INDEX "IX_CounterpartyContacts_LogDbEntryId" ON "CounterpartyContacts" ("LogDbEntryId");

CREATE INDEX "IX_CounterpartyDocuments_CounterpartyId" ON "CounterpartyDocuments" ("CounterpartyId");

CREATE INDEX "IX_CounterpartyDocuments_LogDbEntryId" ON "CounterpartyDocuments" ("LogDbEntryId");

CREATE INDEX "IX_CounterpartyDocuments_UploadedByUserId" ON "CounterpartyDocuments" ("UploadedByUserId");

CREATE INDEX "IX_CounterpartyDocuments_UploadedFileId" ON "CounterpartyDocuments" ("UploadedFileId");


                INSERT INTO "CounterpartyTypes" ("CompanyId", "Name", "SystemCode", "IsSystem", "IsDefault", "Deleted")
                SELECT c."Id", 'Партнёр', 1, true, true, false FROM "Companies" c WHERE c."Deleted" = false;

                INSERT INTO "CounterpartyTypes" ("CompanyId", "Name", "SystemCode", "IsSystem", "IsDefault", "Deleted")
                SELECT c."Id", 'Прочие', NULL, true, false, false FROM "Companies" c WHERE c."Deleted" = false;

                INSERT INTO "CounterpartyTypes" ("CompanyId", "Name", "SystemCode", "IsSystem", "IsDefault", "Deleted")
                SELECT c."Id", 'Автосервис', 2, true, false, false FROM "Companies" c WHERE c."Deleted" = false;



                UPDATE "Counterparties" cp
                SET "CounterpartyTypeId" = ct."Id"
                FROM "CounterpartyTypes" ct
                WHERE ct."CompanyId" = cp."CompanyId" AND ct."SystemCode" = cp."CounterpartyTypeId";



                UPDATE "Counterparties" cp
                SET "CounterpartyTypeId" = NULL
                WHERE cp."CounterpartyTypeId" IS NOT NULL
                  AND NOT EXISTS (SELECT 1 FROM "CounterpartyTypes" ct WHERE ct."Id" = cp."CounterpartyTypeId");


ALTER TABLE "Counterparties" ADD CONSTRAINT "FK_Counterparties_CounterpartyTypes_CounterpartyTypeId" FOREIGN KEY ("CounterpartyTypeId") REFERENCES "CounterpartyTypes" ("Id") ON DELETE RESTRICT;

ALTER TABLE "CounterpartyTypes" ADD CONSTRAINT "FK_CounterpartyTypes_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE RESTRICT;

ALTER TABLE "CounterpartyTypes" ADD CONSTRAINT "FK_CounterpartyTypes_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260613170732_AddCounterpartyFinanceModule', '10.0.1');

COMMIT;

START TRANSACTION;
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (152, '', 'Counterparties / read', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (153, '', 'Counterparties / create', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (154, '', 'Counterparties / update', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (155, '', 'Counterparties / delete', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (156, '', 'Counterparties / reconciliation PDF export', 0);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260613172400_SeedCounterpartyPermissions', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "SalaryDocuments" DROP COLUMN "ElectricCharge";

ALTER TABLE "SalaryDocuments" DROP COLUMN "Petrol";

ALTER TABLE "SalaryDocuments" DROP COLUMN "Salik";

ALTER TABLE "SalaryDocumentLineItems" ADD "PurposeId" bigint;

ALTER TABLE "Purposes" ADD "Category" integer NOT NULL DEFAULT 0;

ALTER TABLE "Purposes" ADD "SalaryReportOrder" integer NOT NULL DEFAULT 0;

CREATE INDEX "IX_SalaryDocumentLineItems_PurposeId" ON "SalaryDocumentLineItems" ("PurposeId");

ALTER TABLE "SalaryDocumentLineItems" ADD CONSTRAINT "FK_SalaryDocumentLineItems_Purposes_PurposeId" FOREIGN KEY ("PurposeId") REFERENCES "Purposes" ("Id") ON DELETE SET NULL;


                UPDATE "Purposes" SET "Category" = 1
                WHERE "PurposeReportTypeId" IN (1, 2, 4);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260613203321_AddPurposeCategoryAndDynamicSalaryExpenses', '10.0.1');

COMMIT;

