START TRANSACTION;
CREATE TABLE "Currencies" (
    "Id" integer NOT NULL,
    "Name" text,
    CONSTRAINT "PK_Currencies" PRIMARY KEY ("Id")
);

CREATE TABLE "LogDbEntries" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    CONSTRAINT "PK_LogDbEntries" PRIMARY KEY ("Id")
);

CREATE TABLE "YoocaOrderStatuses" (
    "Id" integer NOT NULL,
    "Name" text,
    CONSTRAINT "PK_YoocaOrderStatuses" PRIMARY KEY ("Id")
);

CREATE TABLE "YoocaRouteTypes" (
    "Id" integer NOT NULL,
    "Name" text,
    CONSTRAINT "PK_YoocaRouteTypes" PRIMARY KEY ("Id")
);

CREATE TABLE "YoocaServiceTypes" (
    "Id" integer NOT NULL,
    "Name" text,
    CONSTRAINT "PK_YoocaServiceTypes" PRIMARY KEY ("Id")
);

CREATE TABLE "YoocaTariffTypes" (
    "Id" integer NOT NULL,
    "Name" text,
    CONSTRAINT "PK_YoocaTariffTypes" PRIMARY KEY ("Id")
);

CREATE TABLE "YoocaUsers" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "YoocaId" text,
    "FirstName" text,
    "LastName" text,
    "Email" text,
    "Phone" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_YoocaUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "LogDbItems" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "LogDbEntryId" bigint NOT NULL,
    "EntityName" text,
    "Time" timestamp with time zone NOT NULL,
    "FieldName" text,
    "OldValue" text,
    "NewValue" text,
    "UserId" bigint,
    CONSTRAINT "PK_LogDbItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LogDbItems_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_LogDbItems_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
);

CREATE TABLE "YoocaCars" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "YoocaId" text,
    "YoocaUserId" bigint NOT NULL,
    "Brand" text,
    "Model" text,
    "Color" text,
    "ColorHex" text,
    "LicensePlate" text,
    "Transmission" text,
    "Deleted" boolean NOT NULL,
    CONSTRAINT "PK_YoocaCars" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_YoocaCars_YoocaUsers_YoocaUserId" FOREIGN KEY ("YoocaUserId") REFERENCES "YoocaUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "YoocaOrders" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "YoocaId" text,
    "YoocaUserId" bigint NOT NULL,
    "YoocaCarId" bigint NOT NULL,
    "YoocaServiceTypeId" integer NOT NULL,
    "Comment" text,
    "YoocaRouteTypeId" integer NOT NULL,
    "DurationInMinutes" integer NOT NULL,
    "DistanceInMeters" integer NOT NULL,
    "EstimatedMinPrice" numeric NOT NULL,
    "EstimatedMaxPrice" numeric NOT NULL,
    "CurrencyId" integer NOT NULL,
    "YoocaTariffTypeId" integer NOT NULL,
    "AssignedPrice" numeric,
    "PickupTime" timestamp with time zone NOT NULL,
    "IsNow" boolean NOT NULL,
    "FinishedAt" timestamp with time zone NOT NULL,
    "DeclineReason" text,
    "YoocaOrderStatusId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedTime" timestamp with time zone NOT NULL,
    "ModifiedTime" timestamp with time zone NOT NULL,
    "LogDbEntryId" bigint NOT NULL,
    CONSTRAINT "PK_YoocaOrders" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_YoocaOrders_Currencies_CurrencyId" FOREIGN KEY ("CurrencyId") REFERENCES "Currencies" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_YoocaOrders_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_YoocaOrders_YoocaCars_YoocaCarId" FOREIGN KEY ("YoocaCarId") REFERENCES "YoocaCars" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_YoocaOrders_YoocaOrderStatuses_YoocaOrderStatusId" FOREIGN KEY ("YoocaOrderStatusId") REFERENCES "YoocaOrderStatuses" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_YoocaOrders_YoocaRouteTypes_YoocaRouteTypeId" FOREIGN KEY ("YoocaRouteTypeId") REFERENCES "YoocaRouteTypes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_YoocaOrders_YoocaServiceTypes_YoocaServiceTypeId" FOREIGN KEY ("YoocaServiceTypeId") REFERENCES "YoocaServiceTypes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_YoocaOrders_YoocaTariffTypes_YoocaTariffTypeId" FOREIGN KEY ("YoocaTariffTypeId") REFERENCES "YoocaTariffTypes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_YoocaOrders_YoocaUsers_YoocaUserId" FOREIGN KEY ("YoocaUserId") REFERENCES "YoocaUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "YoocaLocations" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Num" integer NOT NULL,
    "TypeCode" integer NOT NULL,
    "YoocaOrderId" bigint NOT NULL,
    "PlaceId" text,
    "Latitude" numeric NOT NULL,
    "Longitude" numeric NOT NULL,
    "Address" text,
    "ShortAddress" text,
    CONSTRAINT "PK_YoocaLocations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_YoocaLocations_YoocaOrders_YoocaOrderId" FOREIGN KEY ("YoocaOrderId") REFERENCES "YoocaOrders" ("Id") ON DELETE CASCADE
);

INSERT INTO "Currencies" ("Id", "Name")
VALUES (1, 'AED');
INSERT INTO "Currencies" ("Id", "Name")
VALUES (2, 'USD');

INSERT INTO "YoocaOrderStatuses" ("Id", "Name")
VALUES (1, 'New');
INSERT INTO "YoocaOrderStatuses" ("Id", "Name")
VALUES (2, 'Priced');
INSERT INTO "YoocaOrderStatuses" ("Id", "Name")
VALUES (3, 'Paid');
INSERT INTO "YoocaOrderStatuses" ("Id", "Name")
VALUES (4, 'Declined');
INSERT INTO "YoocaOrderStatuses" ("Id", "Name")
VALUES (5, 'Closed');

INSERT INTO "YoocaRouteTypes" ("Id", "Name")
VALUES (1, 'one way');
INSERT INTO "YoocaRouteTypes" ("Id", "Name")
VALUES (2, 'round trip');

INSERT INTO "YoocaServiceTypes" ("Id", "Name")
VALUES (1, 'school dropoff');
INSERT INTO "YoocaServiceTypes" ("Id", "Name")
VALUES (2, 'pet to vet');
INSERT INTO "YoocaServiceTypes" ("Id", "Name")
VALUES (3, 'move car a to b');
INSERT INTO "YoocaServiceTypes" ("Id", "Name")
VALUES (4, 'after party');
INSERT INTO "YoocaServiceTypes" ("Id", "Name")
VALUES (5, 'car service');
INSERT INTO "YoocaServiceTypes" ("Id", "Name")
VALUES (6, 'airport transfer');
INSERT INTO "YoocaServiceTypes" ("Id", "Name")
VALUES (7, 'other');

INSERT INTO "YoocaTariffTypes" ("Id", "Name")
VALUES (1, 'per minute');
INSERT INTO "YoocaTariffTypes" ("Id", "Name")
VALUES (2, 'per kilometer');

CREATE INDEX "IX_LogDbItems_LogDbEntryId" ON "LogDbItems" ("LogDbEntryId");

CREATE INDEX "IX_LogDbItems_UserId" ON "LogDbItems" ("UserId");

CREATE UNIQUE INDEX "IX_YoocaCars_YoocaId" ON "YoocaCars" ("YoocaId");

CREATE INDEX "IX_YoocaCars_YoocaUserId" ON "YoocaCars" ("YoocaUserId");

CREATE INDEX "IX_YoocaLocations_YoocaOrderId" ON "YoocaLocations" ("YoocaOrderId");

CREATE INDEX "IX_YoocaOrders_CurrencyId" ON "YoocaOrders" ("CurrencyId");

CREATE INDEX "IX_YoocaOrders_LogDbEntryId" ON "YoocaOrders" ("LogDbEntryId");

CREATE INDEX "IX_YoocaOrders_YoocaCarId" ON "YoocaOrders" ("YoocaCarId");

CREATE UNIQUE INDEX "IX_YoocaOrders_YoocaId" ON "YoocaOrders" ("YoocaId");

CREATE INDEX "IX_YoocaOrders_YoocaOrderStatusId" ON "YoocaOrders" ("YoocaOrderStatusId");

CREATE INDEX "IX_YoocaOrders_YoocaRouteTypeId" ON "YoocaOrders" ("YoocaRouteTypeId");

CREATE INDEX "IX_YoocaOrders_YoocaServiceTypeId" ON "YoocaOrders" ("YoocaServiceTypeId");

CREATE INDEX "IX_YoocaOrders_YoocaTariffTypeId" ON "YoocaOrders" ("YoocaTariffTypeId");

CREATE INDEX "IX_YoocaOrders_YoocaUserId" ON "YoocaOrders" ("YoocaUserId");

CREATE UNIQUE INDEX "IX_YoocaUsers_YoocaId" ON "YoocaUsers" ("YoocaId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260213211701_add_yooca', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "YoocaCars" DROP CONSTRAINT "FK_YoocaCars_YoocaUsers_YoocaUserId";

ALTER TABLE "YoocaOrders" DROP CONSTRAINT "FK_YoocaOrders_YoocaCars_YoocaCarId";

ALTER TABLE "YoocaOrders" DROP CONSTRAINT "FK_YoocaOrders_YoocaUsers_YoocaUserId";

ALTER TABLE "YoocaUsers" ADD "CreatedTime" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "YoocaUsers" ADD "ModifiedTime" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "YoocaOrders" ALTER COLUMN "YoocaUserId" DROP NOT NULL;

ALTER TABLE "YoocaOrders" ALTER COLUMN "YoocaCarId" DROP NOT NULL;

ALTER TABLE "YoocaOrders" ADD "YoocaCarOriginalId" text;

ALTER TABLE "YoocaOrders" ADD "YoocaUserOriginalId" text;

ALTER TABLE "YoocaCars" ALTER COLUMN "YoocaUserId" DROP NOT NULL;

ALTER TABLE "YoocaCars" ADD "CreatedTime" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "YoocaCars" ADD "ModifiedTime" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "YoocaCars" ADD "YoocaUserOriginalId" text;

ALTER TABLE "YoocaCars" ADD CONSTRAINT "FK_YoocaCars_YoocaUsers_YoocaUserId" FOREIGN KEY ("YoocaUserId") REFERENCES "YoocaUsers" ("Id");

ALTER TABLE "YoocaOrders" ADD CONSTRAINT "FK_YoocaOrders_YoocaCars_YoocaCarId" FOREIGN KEY ("YoocaCarId") REFERENCES "YoocaCars" ("Id");

ALTER TABLE "YoocaOrders" ADD CONSTRAINT "FK_YoocaOrders_YoocaUsers_YoocaUserId" FOREIGN KEY ("YoocaUserId") REFERENCES "YoocaUsers" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260214135424_add_yooca_time_and_id_field', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "YoocaUsers" ADD "Deleted" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "YoocaOrders" ALTER COLUMN "PickupTime" DROP NOT NULL;

ALTER TABLE "YoocaOrders" ALTER COLUMN "FinishedAt" DROP NOT NULL;

ALTER TABLE "YoocaOrders" ADD "Deleted" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "YoocaOrders" ADD "FailReason" text;

ALTER TABLE "YoocaOrders" ADD "Failed" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260214190753_yooca_add_delete_fields', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "YoocaUsers" ADD "CompanyId" bigint NOT NULL DEFAULT 0;

INSERT INTO "UserRoles" ("Id", "IsPorlalRole", "Name")
VALUES (7, TRUE, 'Yooca manager');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260214211434_add_yooca_company_field', '10.0.1');

COMMIT;

START TRANSACTION;
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (65, '', 'yooca / read', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (66, '', 'yooca cars / change', 0);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260214212833_add_yooca_access', '10.0.1');

COMMIT;

START TRANSACTION;
INSERT INTO "YoocaOrderStatuses" ("Id", "Name")
VALUES (6, 'Сancel by user');
INSERT INTO "YoocaOrderStatuses" ("Id", "Name")
VALUES (7, 'Driver on way');
INSERT INTO "YoocaOrderStatuses" ("Id", "Name")
VALUES (8, 'In progress');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260217182802_add_yooca_order_statuses', '10.0.1');

COMMIT;

START TRANSACTION;
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (67, '', 'yooca cars / set price', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (68, '', 'yooca cars / decline', 0);

INSERT INTO "YoocaOrderStatuses" ("Id", "Name")
VALUES (9, 'Payment failed');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260221160113_add_yooca_roles', '10.0.1');

COMMIT;

GRANT SELECT, INSERT, DELETE, UPDATE ON "YoocaOrders" TO limousine;
GRANT SELECT, INSERT, DELETE, UPDATE ON "YoocaCars" TO limousine;
GRANT SELECT, INSERT, DELETE, UPDATE ON "YoocaUsers" TO limousine;
GRANT SELECT, INSERT, DELETE, UPDATE ON "YoocaLocations" TO limousine;
GRANT SELECT, INSERT, DELETE, UPDATE ON "YoocaRouteTypes" TO limousine;
GRANT SELECT, INSERT, DELETE, UPDATE ON "YoocaOrderStatuses" TO limousine;
GRANT SELECT, INSERT, DELETE, UPDATE ON "YoocaServiceTypes" TO limousine;
GRANT SELECT, INSERT, DELETE, UPDATE ON "YoocaTariffTypes" TO limousine;
GRANT SELECT, INSERT, DELETE, UPDATE ON "Currencies" TO limousine;
GRANT SELECT, INSERT, DELETE, UPDATE ON "LogDbItems" TO limousine;
GRANT SELECT, INSERT, DELETE, UPDATE ON "LogDbEntries" TO limousine;