START TRANSACTION;
ALTER TABLE "Users" ADD "IsPlatformAdmin" boolean NOT NULL DEFAULT FALSE;

CREATE TABLE "RoleDefinitions" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" text,
    "Code" text,
    "IsSystemPreset" boolean NOT NULL,
    "CompanyId" bigint,
    "Deleted" boolean NOT NULL,
    "LogDbEntryId" bigint,
    CONSTRAINT "PK_RoleDefinitions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RoleDefinitions_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_RoleDefinitions_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id")
);

CREATE TABLE "RoleAccessOverrides" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "RoleDefinitionId" bigint NOT NULL,
    "Code" integer NOT NULL,
    "Allowed" boolean NOT NULL,
    "LogDbEntryId" bigint,
    CONSTRAINT "PK_RoleAccessOverrides" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RoleAccessOverrides_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id"),
    CONSTRAINT "FK_RoleAccessOverrides_RoleDefinitions_RoleDefinitionId" FOREIGN KEY ("RoleDefinitionId") REFERENCES "RoleDefinitions" ("Id") ON DELETE CASCADE
);

CREATE TABLE "RoleModuleGrants" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "RoleDefinitionId" bigint NOT NULL,
    "Module" integer NOT NULL,
    "Level" integer NOT NULL,
    "LogDbEntryId" bigint,
    CONSTRAINT "PK_RoleModuleGrants" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RoleModuleGrants_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id"),
    CONSTRAINT "FK_RoleModuleGrants_RoleDefinitions_RoleDefinitionId" FOREIGN KEY ("RoleDefinitionId") REFERENCES "RoleDefinitions" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserCompanyRoles" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" bigint NOT NULL,
    "CompanyId" bigint,
    "RoleDefinitionId" bigint NOT NULL,
    "LogDbEntryId" bigint,
    CONSTRAINT "PK_UserCompanyRoles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserCompanyRoles_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_UserCompanyRoles_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id"),
    CONSTRAINT "FK_UserCompanyRoles_RoleDefinitions_RoleDefinitionId" FOREIGN KEY ("RoleDefinitionId") REFERENCES "RoleDefinitions" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_UserCompanyRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_RoleAccessOverrides_LogDbEntryId" ON "RoleAccessOverrides" ("LogDbEntryId");

CREATE UNIQUE INDEX "IX_RoleAccessOverrides_RoleDefinitionId_Code" ON "RoleAccessOverrides" ("RoleDefinitionId", "Code");

CREATE UNIQUE INDEX "IX_RoleDefinitions_Code" ON "RoleDefinitions" ("Code") WHERE "CompanyId" IS NULL AND "Code" <> '' AND "Deleted" = false;

CREATE INDEX "IX_RoleDefinitions_CompanyId" ON "RoleDefinitions" ("CompanyId");

CREATE INDEX "IX_RoleDefinitions_LogDbEntryId" ON "RoleDefinitions" ("LogDbEntryId");

CREATE INDEX "IX_RoleModuleGrants_LogDbEntryId" ON "RoleModuleGrants" ("LogDbEntryId");

CREATE UNIQUE INDEX "IX_RoleModuleGrants_RoleDefinitionId_Module" ON "RoleModuleGrants" ("RoleDefinitionId", "Module");

CREATE INDEX "IX_UserCompanyRoles_CompanyId" ON "UserCompanyRoles" ("CompanyId");

CREATE INDEX "IX_UserCompanyRoles_LogDbEntryId" ON "UserCompanyRoles" ("LogDbEntryId");

CREATE INDEX "IX_UserCompanyRoles_RoleDefinitionId" ON "UserCompanyRoles" ("RoleDefinitionId");

CREATE UNIQUE INDEX "IX_UserCompanyRoles_UserId_CompanyId_RoleDefinitionId" ON "UserCompanyRoles" ("UserId", "CompanyId", "RoleDefinitionId");

CREATE UNIQUE INDEX "IX_UserCompanyRoles_UserId_RoleDefinitionId" ON "UserCompanyRoles" ("UserId", "RoleDefinitionId") WHERE "CompanyId" IS NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260819020616_AddModularRbac', '10.0.1');

COMMIT;

START TRANSACTION;
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (224, '', 'Tasks / see all boards and tasks', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (225, '', 'Tasks / reassign despite board setting', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (226, '', 'Tasks / restore a finished task', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (227, '', 'Tasks / manage any team''s boards', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (228, '', 'Illegal trips / mark processed', 0);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260819035649_AddPhase4AccessCodes', '10.0.1');

COMMIT;

START TRANSACTION;
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (229, 'The holder''s phone number is added to the WhatsApp group the CRM creates with a driver.', 'Driver WhatsApp group / join', 0);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260819044749_AddDriverWhatsappGroupJoinAccess', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "Users" ADD "ModularAccessSinceUtc" timestamp with time zone;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260819090439_AddUserModularAccessMarker', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "TaskNotifications" ADD "ModifiedTime" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260819193258_AddTaskNotificationModifiedTime', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "TriggerRules" ADD "Priority" integer NOT NULL DEFAULT 0;

CREATE TABLE "EventLogEntries" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" bigint NOT NULL,
    "CompanyName" text,
    "TriggerRuleId" bigint,
    "Priority" integer NOT NULL,
    "Title" text,
    "Body" text,
    "DriverId" bigint,
    "Deleted" boolean NOT NULL,
    "LegacySource" integer NOT NULL,
    "LegacyId" bigint,
    "CreatedTime" timestamp with time zone NOT NULL,
    "ModifiedTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_EventLogEntries" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EventLogEntries_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_EventLogEntries_TriggerRules_TriggerRuleId" FOREIGN KEY ("TriggerRuleId") REFERENCES "TriggerRules" ("Id") ON DELETE SET NULL
);

CREATE TABLE "Notifications" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" bigint NOT NULL,
    "CompanyId" bigint,
    "CompanyName" text,
    "Module" integer NOT NULL,
    "TemplateKey" text,
    "ParamsJson" text,
    "Priority" integer NOT NULL,
    "RequiresAction" boolean NOT NULL,
    "Title" text,
    "Body" text,
    "EntityType" text,
    "EntityId" bigint,
    "GroupKey" text,
    "IsRead" boolean NOT NULL,
    "ReadAt" timestamp with time zone,
    "Deleted" boolean NOT NULL,
    "LegacySource" integer NOT NULL,
    "LegacyId" bigint,
    "CreatedTime" timestamp with time zone NOT NULL,
    "ModifiedTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Notifications_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Notifications_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "EventLogReads" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "EventLogEntryId" bigint NOT NULL,
    "UserId" bigint NOT NULL,
    "ReadAt" timestamp with time zone,
    "Kind" integer NOT NULL,
    "CreatedTime" timestamp with time zone NOT NULL,
    "ModifiedTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_EventLogReads" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EventLogReads_EventLogEntries_EventLogEntryId" FOREIGN KEY ("EventLogEntryId") REFERENCES "EventLogEntries" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_EventLogReads_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_EventLogEntries_Feed" ON "EventLogEntries" ("CompanyId", "CreatedTime");

CREATE INDEX "IX_EventLogEntries_Priority" ON "EventLogEntries" ("CompanyId", "Priority", "CreatedTime");

CREATE INDEX "IX_EventLogEntries_TriggerRuleId" ON "EventLogEntries" ("TriggerRuleId");

CREATE UNIQUE INDEX "UQ_EventLogEntries_Legacy" ON "EventLogEntries" ("LegacySource", "LegacyId") WHERE "LegacyId" IS NOT NULL;

CREATE INDEX "IX_EventLogReads_UserEntry" ON "EventLogReads" ("UserId", "EventLogEntryId");

CREATE UNIQUE INDEX "UQ_EventLogReads_EntryUser" ON "EventLogReads" ("EventLogEntryId", "UserId");

CREATE INDEX "IX_Notifications_CompanyId" ON "Notifications" ("CompanyId");

CREATE INDEX "IX_Notifications_Unread" ON "Notifications" ("UserId", "CompanyId", "Module", "CreatedTime") WHERE NOT "IsRead" AND NOT "Deleted";

CREATE UNIQUE INDEX "UQ_Notifications_GroupKey" ON "Notifications" ("UserId", "GroupKey") WHERE "GroupKey" IS NOT NULL;

CREATE UNIQUE INDEX "UQ_Notifications_Legacy" ON "Notifications" ("LegacySource", "LegacyId") WHERE "LegacyId" IS NOT NULL;

UPDATE "TriggerRules" SET "Priority" = 1
WHERE NOT "Deleted" AND "Name" IN (
    'Водитель заблокирован',
    'Отмена заказа',
    '‼️Поездка без заказа в системе');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260820043448_AddUnifiedNotifications', '10.0.1');

COMMIT;

