START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260921181841_AddDriverCarSightings') THEN
    CREATE TABLE "DriverCarSightings" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "CompanyId" bigint NOT NULL,
        "UserId" bigint NOT NULL,
        "Date" timestamp with time zone NOT NULL,
        "AggregatorId" integer NOT NULL,
        "Kind" integer NOT NULL,
        "Plate" text NOT NULL,
        "ExternalCarId" text NOT NULL,
        "CarId" bigint,
        "Count" integer NOT NULL,
        "FirstSeen" timestamp with time zone NOT NULL,
        "LastSeen" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_DriverCarSightings" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260921181841_AddDriverCarSightings') THEN
    CREATE INDEX "IX_DriverCarSightings_CompanyId_Date" ON "DriverCarSightings" ("CompanyId", "Date");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260921181841_AddDriverCarSightings') THEN
    CREATE UNIQUE INDEX "IX_DriverCarSightings_CompanyId_UserId_Date_AggregatorId_Kind_~" ON "DriverCarSightings" ("CompanyId", "UserId", "Date", "AggregatorId", "Kind", "Plate", "ExternalCarId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260921181841_AddDriverCarSightings') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260921181841_AddDriverCarSightings', '10.0.1');
    END IF;
END $EF$;
COMMIT;


-- 20260921182917_AddTransactionsCarIdDateTimeIndex: вне транзакции и без DO-блока —
-- CONCURRENTLY внутри функции PostgreSQL не выполняет. Команды сами идемпотентны.
CREATE INDEX CONCURRENTLY IF NOT EXISTS "IX_Transactions_CarId_DateTime"
ON "Transactions" ("CarId", "DateTime");

DROP INDEX CONCURRENTLY IF EXISTS "IX_Transactions_CarId";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260921182917_AddTransactionsCarIdDateTimeIndex', '10.0.1')
ON CONFLICT ("MigrationId") DO NOTHING;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260921185203_AddDriverDayCarSource') THEN
    ALTER TABLE "DriverSummaries" ADD "CarAmbiguous" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260921185203_AddDriverDayCarSource') THEN
    ALTER TABLE "DriverSummaries" ADD "CarResolvedAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260921185203_AddDriverDayCarSource') THEN
    ALTER TABLE "DriverSummaries" ADD "CarSource" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260921185203_AddDriverDayCarSource') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260921185203_AddDriverDayCarSource', '10.0.1');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260921192745_AddCompanyMailboxes') THEN
    CREATE TABLE "CompanyMailboxes" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "CompanyId" bigint NOT NULL,
        "Name" text,
        "Provider" integer NOT NULL,
        "ImapHost" text,
        "ImapPort" integer NOT NULL,
        "ImapUseTls" boolean NOT NULL,
        "RejectUnauthorized" boolean NOT NULL,
        "Username" text,
        "Password" text,
        "LastCheckAt" timestamp with time zone,
        "LastCheckOk" boolean,
        "LastCheckError" text,
        "Deleted" boolean NOT NULL,
        "CreatedTime" timestamp with time zone NOT NULL,
        "ModifiedTime" timestamp with time zone NOT NULL,
        "LogDbEntryId" bigint,
        CONSTRAINT "PK_CompanyMailboxes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CompanyMailboxes_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_CompanyMailboxes_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260921192745_AddCompanyMailboxes') THEN
    CREATE TABLE "CompanyMailboxUsages" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "CompanyId" bigint NOT NULL,
        "UsageKey" text,
        "MailboxId" bigint NOT NULL,
        "FromFilter" text,
        "SubjectFilter" text,
        "CreatedTime" timestamp with time zone NOT NULL,
        "ModifiedTime" timestamp with time zone NOT NULL,
        "LogDbEntryId" bigint,
        CONSTRAINT "PK_CompanyMailboxUsages" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CompanyMailboxUsages_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_CompanyMailboxUsages_CompanyMailboxes_MailboxId" FOREIGN KEY ("MailboxId") REFERENCES "CompanyMailboxes" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_CompanyMailboxUsages_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260921192745_AddCompanyMailboxes') THEN
    CREATE INDEX "IX_CompanyMailboxes_CompanyId" ON "CompanyMailboxes" ("CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260921192745_AddCompanyMailboxes') THEN
    CREATE INDEX "IX_CompanyMailboxes_LogDbEntryId" ON "CompanyMailboxes" ("LogDbEntryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260921192745_AddCompanyMailboxes') THEN
    CREATE UNIQUE INDEX "IX_CompanyMailboxUsages_CompanyId_UsageKey" ON "CompanyMailboxUsages" ("CompanyId", "UsageKey");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260921192745_AddCompanyMailboxes') THEN
    CREATE INDEX "IX_CompanyMailboxUsages_LogDbEntryId" ON "CompanyMailboxUsages" ("LogDbEntryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260921192745_AddCompanyMailboxes') THEN
    CREATE INDEX "IX_CompanyMailboxUsages_MailboxId" ON "CompanyMailboxUsages" ("MailboxId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260921192745_AddCompanyMailboxes') THEN
    INSERT INTO "CompanyMailboxes" ("CompanyId", "Name", "Provider", "ImapHost", "ImapPort", "ImapUseTls",
        "RejectUnauthorized", "Username", "Password", "Deleted", "CreatedTime", "ModifiedTime")
    SELECT DISTINCT c."CompanyId", c."ConfigJson"->'otpMail'->>'user', 1, 'imap.gmail.com', 993, true,
        false, c."ConfigJson"->'otpMail'->>'user', COALESCE(c."ConfigJson"->'otpMail'->>'password', ''),
        false, now(), now()
    FROM "CompanyExternalServiceConfigs" c
    WHERE c."ExternalServiceKey" IN ('enoc', 'rta')
      AND COALESCE(c."ConfigJson"->'otpMail'->>'user', '') <> '';

    INSERT INTO "CompanyMailboxUsages" ("CompanyId", "UsageKey", "MailboxId", "CreatedTime", "ModifiedTime")
    SELECT c."CompanyId", 'otp.' || c."ExternalServiceKey", m."Id", now(), now()
    FROM "CompanyExternalServiceConfigs" c
    JOIN "CompanyMailboxes" m
      ON m."CompanyId" = c."CompanyId"
     AND m."Username" = c."ConfigJson"->'otpMail'->>'user'
     AND m."Password" = COALESCE(c."ConfigJson"->'otpMail'->>'password', '')
    WHERE c."ExternalServiceKey" IN ('enoc', 'rta')
      AND COALESCE(c."ConfigJson"->'otpMail'->>'user', '') <> '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260921192745_AddCompanyMailboxes') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260921192745_AddCompanyMailboxes', '10.0.1');
    END IF;
END $EF$;
COMMIT;

