START TRANSACTION;
ALTER TABLE "BotTasks" ADD "CompletedAt" timestamp with time zone;

ALTER TABLE "BotTasks" ADD "CompletionNotes" text;

ALTER TABLE "BotTasks" ADD "ConfirmedAt" timestamp with time zone;

ALTER TABLE "BotTasks" ADD "GroupMessageId" integer;

ALTER TABLE "BotTasks" ADD "RawInput" text;

ALTER TABLE "BotTasks" ADD "ReminderCount" integer NOT NULL DEFAULT 0;

ALTER TABLE "BotTasks" ADD "TargetGroupChatId" bigint;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260416190926_addBotTaskColumns', '10.0.1');

COMMIT;

START TRANSACTION;
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (101, '', 'Salaries / read', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (102, '', 'Salaries / calculate', 0);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260418205650_add_accesse_salary', '10.0.1');

COMMIT;

START TRANSACTION;
CREATE TABLE "TriggerRules" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" bigint NOT NULL,
    "Name" text,
    "Description" text,
    "ConditionJson" text,
    "MessageTemplate" text,
    "CooldownSeconds" integer NOT NULL,
    "AllowWhatsapp" boolean NOT NULL,
    "AllowTelegram" boolean NOT NULL,
    "AllowPortal" boolean NOT NULL,
    "Disabled" boolean NOT NULL,
    "Deleted" boolean NOT NULL,
    "CreatedTime" timestamp with time zone NOT NULL,
    "ModifiedTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TriggerRules" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TriggerRules_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_TriggerRules_CompanyId" ON "TriggerRules" ("CompanyId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260420175046_add_trigger_rules', '10.0.1');

COMMIT;

START TRANSACTION;
INSERT INTO "TransactionTypes" ("Id", "Description", "IsAggrTransaction", "IsDebtPayment", "IsFine", "Name", "ShortName")
VALUES (43, '', FALSE, FALSE, FALSE, 'Damage', NULL);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260425193233_add_damage_transaction_type', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "TaskAssignees" ADD "LogDbEntryId" bigint;

CREATE INDEX "IX_TaskAssignees_LogDbEntryId" ON "TaskAssignees" ("LogDbEntryId");

ALTER TABLE "TaskAssignees" ADD CONSTRAINT "FK_TaskAssignees_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260427075805_AddAuditToTaskAssignee', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "TriggerRules" ADD "SustainedForSeconds" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260429181322_AddSustainedForSecondsToTriggerRule', '10.0.1');

COMMIT;

