START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    ALTER TABLE "DriverCarChanges" ADD "HandoverConfirmed" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    ALTER TABLE "DriverCarChanges" ADD "ManualOdometerEnd" numeric;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    ALTER TABLE "DriverCarChanges" ADD "ManualOdometerStart" numeric;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    ALTER TABLE "Companies" ADD "CarDetectionSources" integer NOT NULL DEFAULT 3;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    ALTER TABLE "Companies" ADD "CarDriverBackdateCapHours" integer NOT NULL DEFAULT 4;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    ALTER TABLE "Companies" ADD "FuelAutoCloseEnabled" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    ALTER TABLE "Companies" ADD "FuelMonthEndTrueUp" boolean NOT NULL DEFAULT TRUE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    ALTER TABLE "Companies" ADD "FuelNormAlertThreshold" numeric NOT NULL DEFAULT 0.2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    ALTER TABLE "Companies" ADD "FuelNormWindowMonths" integer NOT NULL DEFAULT 3;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    ALTER TABLE "Companies" ADD "FuelSilenceAlertDay" integer NOT NULL DEFAULT 3;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    ALTER TABLE "Companies" ADD "FuelUnderReportThreshold" numeric NOT NULL DEFAULT 0.7;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    ALTER TABLE "Companies" ADD "IdleHourKmEquivalent" numeric NOT NULL DEFAULT 8.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    ALTER TABLE "CarDailyMileages" ADD "IdleHours" numeric;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    CREATE TABLE "CarDayDriverMileages" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "CompanyId" bigint NOT NULL,
        "CarId" bigint NOT NULL,
        "LocalDay" date NOT NULL,
        "DriverCarChangeId" bigint,
        "DriverId" bigint,
        "Hours" numeric NOT NULL,
        "Km" numeric NOT NULL,
        "IdleHours" numeric NOT NULL,
        "Source" integer NOT NULL,
        "CreatedTime" timestamp with time zone NOT NULL,
        "ModifiedTime" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_CarDayDriverMileages" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CarDayDriverMileages_Cars_CarId" FOREIGN KEY ("CarId") REFERENCES "Cars" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_CarDayDriverMileages_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_CarDayDriverMileages_DriverCarChanges_DriverCarChangeId" FOREIGN KEY ("DriverCarChangeId") REFERENCES "DriverCarChanges" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    CREATE TABLE "CarFuelRates" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "CompanyId" bigint NOT NULL,
        "CarId" bigint NOT NULL,
        "PurposeId" bigint NOT NULL,
        "LocalMonth" date NOT NULL,
        "RateAedPerEqKm" numeric,
        "Source" integer NOT NULL,
        "WindowMonths" integer NOT NULL,
        "WindowAmount" numeric NOT NULL,
        "WindowEquivalentKm" numeric NOT NULL,
        "CreatedTime" timestamp with time zone NOT NULL,
        "ModifiedTime" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_CarFuelRates" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CarFuelRates_Cars_CarId" FOREIGN KEY ("CarId") REFERENCES "Cars" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_CarFuelRates_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_CarFuelRates_Purposes_PurposeId" FOREIGN KEY ("PurposeId") REFERENCES "Purposes" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    CREATE TABLE "CarHourlyMileages" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "CompanyId" bigint NOT NULL,
        "CarId" bigint NOT NULL,
        "HourStartUtc" timestamp with time zone NOT NULL,
        "Km" numeric NOT NULL,
        "IdleHours" numeric NOT NULL,
        "Pings" integer NOT NULL,
        "MovingPings" integer NOT NULL,
        "CreatedTime" timestamp with time zone NOT NULL,
        "ModifiedTime" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_CarHourlyMileages" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CarHourlyMileages_Cars_CarId" FOREIGN KEY ("CarId") REFERENCES "Cars" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_CarHourlyMileages_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    CREATE TABLE "CompanyFuelModeChanges" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "CompanyId" bigint NOT NULL,
        "EffectiveMonth" date NOT NULL,
        "Mode" integer NOT NULL,
        "UserId" bigint NOT NULL,
        "CreatedTime" timestamp with time zone NOT NULL,
        "ModifiedTime" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_CompanyFuelModeChanges" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CompanyFuelModeChanges_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    CREATE TABLE "CompanyModelFuelRates" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "CompanyId" bigint NOT NULL,
        "CarModelId" bigint NOT NULL,
        "PurposeId" bigint NOT NULL,
        "RateAedPerEqKm" numeric NOT NULL,
        "Comment" text,
        "CreatedTime" timestamp with time zone NOT NULL,
        "ModifiedTime" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_CompanyModelFuelRates" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CompanyModelFuelRates_CarModels_CarModelId" FOREIGN KEY ("CarModelId") REFERENCES "CarModels" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_CompanyModelFuelRates_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_CompanyModelFuelRates_Purposes_PurposeId" FOREIGN KEY ("PurposeId") REFERENCES "Purposes" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    CREATE TABLE "FuelMonthCloses" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "CompanyId" bigint NOT NULL,
        "LocalMonth" date NOT NULL,
        "ClosedByUserId" bigint,
        "IdleHourKmEquivalent" numeric NOT NULL,
        "TrueUp" boolean NOT NULL,
        "SignalsJson" text,
        "Reverted" boolean NOT NULL,
        "RevertedByUserId" bigint,
        "RevertedTime" timestamp with time zone,
        "CreatedTime" timestamp with time zone NOT NULL,
        "ModifiedTime" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_FuelMonthCloses" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FuelMonthCloses_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    CREATE TABLE "CarFuelMonths" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "CompanyId" bigint NOT NULL,
        "FuelMonthCloseId" bigint NOT NULL,
        "CarId" bigint NOT NULL,
        "PurposeId" bigint NOT NULL,
        "ActualAmount" numeric NOT NULL,
        "CarryInAmount" numeric NOT NULL,
        "PoolAmount" numeric NOT NULL,
        "CarryOutAmount" numeric NOT NULL,
        "EquivalentKm" numeric NOT NULL,
        "UnassignedEquivalentKm" numeric NOT NULL,
        "UnassignedAmount" numeric NOT NULL,
        "CarFuelRateId" bigint,
        "RateAedPerEqKm" numeric,
        "CreatedTime" timestamp with time zone NOT NULL,
        "ModifiedTime" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_CarFuelMonths" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CarFuelMonths_CarFuelRates_CarFuelRateId" FOREIGN KEY ("CarFuelRateId") REFERENCES "CarFuelRates" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_CarFuelMonths_Cars_CarId" FOREIGN KEY ("CarId") REFERENCES "Cars" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_CarFuelMonths_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_CarFuelMonths_FuelMonthCloses_FuelMonthCloseId" FOREIGN KEY ("FuelMonthCloseId") REFERENCES "FuelMonthCloses" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_CarFuelMonths_Purposes_PurposeId" FOREIGN KEY ("PurposeId") REFERENCES "Purposes" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    CREATE TABLE "DriverFuelCharges" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "CompanyId" bigint NOT NULL,
        "CarFuelMonthId" bigint NOT NULL,
        "DriverId" bigint NOT NULL,
        "Km" numeric NOT NULL,
        "IdleHours" numeric NOT NULL,
        "EquivalentKm" numeric NOT NULL,
        "Share" numeric NOT NULL,
        "NonTrackerShare" numeric NOT NULL,
        "Amount" numeric NOT NULL,
        "ResultTransactionId" bigint,
        "CreatedTime" timestamp with time zone NOT NULL,
        "ModifiedTime" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_DriverFuelCharges" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_DriverFuelCharges_CarFuelMonths_CarFuelMonthId" FOREIGN KEY ("CarFuelMonthId") REFERENCES "CarFuelMonths" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_DriverFuelCharges_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_DriverFuelCharges_Transactions_ResultTransactionId" FOREIGN KEY ("ResultTransactionId") REFERENCES "Transactions" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_DriverFuelCharges_Users_DriverId" FOREIGN KEY ("DriverId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    INSERT INTO "TransactionTypes" ("Id", "Description", "IsAggrTransaction", "IsDebtPayment", "IsFine", "Name", "ShortName")
    VALUES (50, 'Driver''s share of the car''s fuel for a closed month (Formula mode)', FALSE, FALSE, FALSE, 'Fuel allocation', NULL);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    CREATE INDEX "IX_CarDayDriverMileages_CarId_LocalDay" ON "CarDayDriverMileages" ("CarId", "LocalDay");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    CREATE UNIQUE INDEX "IX_CarDayDriverMileages_CarId_LocalDay_Unassigned" ON "CarDayDriverMileages" ("CarId", "LocalDay") WHERE "DriverCarChangeId" IS NULL AND "DriverId" IS NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    CREATE INDEX "IX_CarDayDriverMileages_CompanyId_LocalDay" ON "CarDayDriverMileages" ("CompanyId", "LocalDay");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    CREATE INDEX "IX_CarDayDriverMileages_DriverId_LocalDay" ON "CarDayDriverMileages" ("DriverId", "LocalDay");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    CREATE UNIQUE INDEX "IX_CarDayDriverMileages_Interval_LocalDay" ON "CarDayDriverMileages" ("DriverCarChangeId", "LocalDay") WHERE "DriverCarChangeId" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    CREATE INDEX "IX_CarFuelMonths_CarFuelRateId" ON "CarFuelMonths" ("CarFuelRateId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    CREATE INDEX "IX_CarFuelMonths_CarId" ON "CarFuelMonths" ("CarId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    CREATE INDEX "IX_CarFuelMonths_CompanyId_CarId_PurposeId" ON "CarFuelMonths" ("CompanyId", "CarId", "PurposeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    CREATE INDEX "IX_CarFuelMonths_FuelMonthCloseId" ON "CarFuelMonths" ("FuelMonthCloseId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    CREATE INDEX "IX_CarFuelMonths_PurposeId" ON "CarFuelMonths" ("PurposeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    CREATE UNIQUE INDEX "IX_CarFuelRates_CarId_PurposeId_LocalMonth" ON "CarFuelRates" ("CarId", "PurposeId", "LocalMonth");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    CREATE INDEX "IX_CarFuelRates_CompanyId_LocalMonth" ON "CarFuelRates" ("CompanyId", "LocalMonth");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    CREATE INDEX "IX_CarFuelRates_PurposeId" ON "CarFuelRates" ("PurposeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    CREATE UNIQUE INDEX "IX_CarHourlyMileages_CarId_HourStartUtc" ON "CarHourlyMileages" ("CarId", "HourStartUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    CREATE INDEX "IX_CarHourlyMileages_CompanyId_HourStartUtc" ON "CarHourlyMileages" ("CompanyId", "HourStartUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    CREATE INDEX "IX_CompanyFuelModeChanges_CompanyId_EffectiveMonth" ON "CompanyFuelModeChanges" ("CompanyId", "EffectiveMonth");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    CREATE INDEX "IX_CompanyModelFuelRates_CarModelId" ON "CompanyModelFuelRates" ("CarModelId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    CREATE UNIQUE INDEX "IX_CompanyModelFuelRates_CompanyId_CarModelId_PurposeId" ON "CompanyModelFuelRates" ("CompanyId", "CarModelId", "PurposeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    CREATE INDEX "IX_CompanyModelFuelRates_PurposeId" ON "CompanyModelFuelRates" ("PurposeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    CREATE INDEX "IX_DriverFuelCharges_CarFuelMonthId" ON "DriverFuelCharges" ("CarFuelMonthId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    CREATE INDEX "IX_DriverFuelCharges_CompanyId_DriverId" ON "DriverFuelCharges" ("CompanyId", "DriverId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    CREATE INDEX "IX_DriverFuelCharges_DriverId" ON "DriverFuelCharges" ("DriverId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    CREATE INDEX "IX_DriverFuelCharges_ResultTransactionId" ON "DriverFuelCharges" ("ResultTransactionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    CREATE UNIQUE INDEX "IX_FuelMonthCloses_CompanyId_LocalMonth_Active" ON "FuelMonthCloses" ("CompanyId", "LocalMonth") WHERE NOT "Reverted";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    INSERT INTO "RoleAccessOverrides" ("RoleDefinitionId", "Code", "Allowed")
    SELECT r."Id", x.code, x.allowed
    FROM "RoleDefinitions" r
    JOIN LATERAL (
        -- 261 SHIFT_READ: Fleet ≥ View, только ADMIN
        SELECT 261 AS code, false AS allowed WHERE r."Code" <> 'ADMIN'
            AND EXISTS (SELECT 1 FROM "RoleModuleGrants" g WHERE g."RoleDefinitionId" = r."Id" AND g."Module" = 0 AND g."Level" >= 1)
        UNION ALL
        -- 262 SHIFT_UPDATE: Fleet/Admin, у ADMIN Fleet = Manager
        SELECT 262, true WHERE r."Code" = 'ADMIN'
        UNION ALL
        -- 263 FUEL_ALLOCATION_READ: Finance ≥ View, только ADMIN и ACCOUNTING
        SELECT 263, false WHERE r."Code" NOT IN ('ADMIN', 'ACCOUNTING')
            AND EXISTS (SELECT 1 FROM "RoleModuleGrants" g WHERE g."RoleDefinitionId" = r."Id" AND g."Module" = 2 AND g."Level" >= 1)
        UNION ALL
        -- 264 FUEL_ALLOCATION_UPDATE: Finance ≥ Manager, только ADMIN и ACCOUNTING
        SELECT 264, false WHERE r."Code" NOT IN ('ADMIN', 'ACCOUNTING')
            AND EXISTS (SELECT 1 FROM "RoleModuleGrants" g WHERE g."RoleDefinitionId" = r."Id" AND g."Module" = 2 AND g."Level" >= 3)
    ) x ON true
    WHERE NOT r."Deleted"
    ON CONFLICT ("RoleDefinitionId", "Code") DO NOTHING;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260924173530_ShiftFuelAllocation') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260924173530_ShiftFuelAllocation', '10.0.1');
    END IF;
END $EF$;
COMMIT;

