START TRANSACTION;
ALTER TABLE "Companies" ADD "UtcOffsetMinutes" integer NOT NULL DEFAULT 240;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260719023232_AddCompanyUtcOffsetMinutes', '10.0.1');

COMMIT;

START TRANSACTION;
CREATE TABLE "AggregatorCarBindings" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "AggregatorId" integer NOT NULL,
    "CompanyId" bigint NOT NULL,
    "AggregatorExternalId" text NOT NULL,
    "CarId" bigint NOT NULL,
    "BindingMode" integer NOT NULL,
    "CreatedTime" timestamp with time zone NOT NULL,
    "ModifiedTime" timestamp with time zone NOT NULL,
    "AggregatorPlate" text,
    "AggregatorBrand" text,
    "AggregatorModel" text,
    CONSTRAINT "PK_AggregatorCarBindings" PRIMARY KEY ("Id")
);

CREATE TABLE "AggregatorDriverBindings" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "AggregatorId" integer NOT NULL,
    "CompanyId" bigint NOT NULL,
    "AggregatorExternalId" text NOT NULL,
    "UserId" bigint NOT NULL,
    "BindingMode" integer NOT NULL,
    "CreatedTime" timestamp with time zone NOT NULL,
    "ModifiedTime" timestamp with time zone NOT NULL,
    "AggregatorDriverName" text,
    "AggregatorPhone" text,
    "AggregatorCarSign" text,
    "AggregatorEmail" text,
    CONSTRAINT "PK_AggregatorDriverBindings" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_AggregatorCarBindings_AggregatorId_CompanyId_AggregatorExte~" ON "AggregatorCarBindings" ("AggregatorId", "CompanyId", "AggregatorExternalId");

CREATE UNIQUE INDEX "IX_AggregatorDriverBindings_AggregatorId_CompanyId_AggregatorE~" ON "AggregatorDriverBindings" ("AggregatorId", "CompanyId", "AggregatorExternalId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260720155112_AddAggregatorBindings', '10.0.1');

COMMIT;

START TRANSACTION;

CREATE TABLE "AggregatorRawArchives" (
    "Id"                    bigint GENERATED BY DEFAULT AS IDENTITY,
    "AggregatorId"          integer NOT NULL,
    "CompanyId"             bigint  NOT NULL,
    "Kind"                  integer NOT NULL,
    "AggregatorExternalId"  text    NOT NULL DEFAULT '',
    "PolledAt"              timestamptz NOT NULL,
    "RawJson"               text    NOT NULL DEFAULT '',
    CONSTRAINT "PK_AggregatorRawArchives" PRIMARY KEY ("Id", "PolledAt")
) PARTITION BY RANGE ("PolledAt");
CREATE INDEX "IX_RawArchive_lookup" ON "AggregatorRawArchives" ("AggregatorId", "CompanyId", "Kind", "PolledAt");



DO $$
DECLARE
    m timestamptz;
    i int;
BEGIN
    FOR i IN 0..1 LOOP
        m := (date_trunc('month', (now() AT TIME ZONE 'UTC')) + (i || ' month')::interval) AT TIME ZONE 'UTC';
        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS %I PARTITION OF "AggregatorRawArchives" FOR VALUES FROM (%L) TO (%L)',
            'AggregatorRawArchives_' || to_char(m AT TIME ZONE 'UTC', 'YYYYMM'),
            m,
            m + interval '1 month');
    END LOOP;
END $$;



CREATE TABLE IF NOT EXISTS "AggregatorRawArchives_default"
    PARTITION OF "AggregatorRawArchives" DEFAULT;


INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260720174542_AddAggregatorRawArchive', '10.0.1');

COMMIT;

/*
START TRANSACTION;
DROP TABLE "CareemDriverCoordinates";

DROP TABLE "CareemDriverStatuses";

DROP TABLE "CareemTokens";

DROP TABLE "CareemTransactions";

DROP TABLE "CareemCars";

DROP TABLE "CareemDrivers";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260720183114_RetireCareemTables', '10.0.1');

COMMIT;

 */

START TRANSACTION;
CREATE INDEX "IX_AggregatorDriverBindings_CompanyId_UserId" ON "AggregatorDriverBindings" ("CompanyId", "UserId");

CREATE INDEX "IX_AggregatorCarBindings_CompanyId_CarId" ON "AggregatorCarBindings" ("CompanyId", "CarId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260721024316_AddBindingAntiJoinIndexes', '10.0.1');

COMMIT;


 ALTER TABLE "AggregatorRawArchives"          OWNER TO limousine;
 ALTER TABLE "AggregatorRawArchives_202607" OWNER TO limousine;
 ALTER TABLE "AggregatorRawArchives_202608" OWNER TO limousine;
 ALTER SEQUENCE "AggregatorRawArchives_Id_seq" OWNER TO limousine;




-- Backfill Yango driver/car bindings + display snapshot from the existing mirror tables.
--
-- WHEN: after the Phase 0 migrations are applied, and BEFORE turning PublishToCore=true for a company.
-- SAFETY: idempotent (WHERE NOT EXISTS), insert-only, touches no existing row.
--
-- Enum values are stored as ints: AggregatorType.YANGO = 0, TransactionDriverBinding.Auto = 1.
--
-- The snapshot is filled from the mirror's own columns, INCLUDING phone and car sign.
--
-- The plan left those two empty, expecting the core resolver to re-stamp them on the first poll. That only
-- holds in publish mode. A company still on PublishToCore=false never produces messages, so nothing would
-- ever re-stamp them — and because the readers fall back to the mirror only when the binding ROW is
-- missing (not when a field is empty), a backfilled legacy company would show a driver card with a name but
-- no phone and no car sign. Filling them here keeps every company's card intact regardless of mode.
--
-- Email stays empty: the mirror does not carry one, so there is nothing to copy.
--
-- BindingMode = Auto (1), not Manual: these are resolver-created links, and Manual would permanently
-- freeze them against re-resolution.

BEGIN;

INSERT INTO "AggregatorDriverBindings"
  ("AggregatorId","CompanyId","AggregatorExternalId","UserId","BindingMode","CreatedTime","ModifiedTime",
   "AggregatorDriverName","AggregatorPhone","AggregatorCarSign","AggregatorEmail")
SELECT 0, d."CompanyId", d."YaId", d."UserId", 1,
       now() AT TIME ZONE 'utc', now() AT TIME ZONE 'utc',
       trim(coalesce(d."LastName",'') || ' ' || coalesce(d."FirstName",'')),
       coalesce(d."Phones"[1], ''),                 -- text[], 1-indexed; resolver also takes the first
       coalesce(yc."NormalizedNumber", ''),
       ''
FROM "YandexDrivers" d
LEFT JOIN "YandexCars" yc ON yc."Id" = d."YandexCarId"
WHERE d."UserId" IS NOT NULL
  AND d."CompanyId" IS NOT NULL
  AND d."YaId" <> ''
  AND NOT EXISTS (
      SELECT 1 FROM "AggregatorDriverBindings" b
      WHERE b."AggregatorId" = 0
        AND b."CompanyId" = d."CompanyId"
        AND b."AggregatorExternalId" = d."YaId");

INSERT INTO "AggregatorCarBindings"
  ("AggregatorId","CompanyId","AggregatorExternalId","CarId","BindingMode","CreatedTime","ModifiedTime",
   "AggregatorPlate","AggregatorBrand","AggregatorModel")
SELECT 0, c."CompanyId", c."YaId", c."CarId", 1,
       now() AT TIME ZONE 'utc', now() AT TIME ZONE 'utc',
       coalesce(c."NormalizedNumber",''), coalesce(c."Brand",''), coalesce(c."Model",'')
FROM "YandexCars" c
WHERE c."CarId" IS NOT NULL
  AND c."CompanyId" IS NOT NULL
  AND c."YaId" <> ''
  AND NOT EXISTS (
      SELECT 1 FROM "AggregatorCarBindings" b
      WHERE b."AggregatorId" = 0
        AND b."CompanyId" = c."CompanyId"
        AND b."AggregatorExternalId" = c."YaId");

COMMIT;

-- ── VERIFY ───────────────────────────────────────────────────────────────────────────────────────────
-- Both queries must return zero rows. A non-empty result means some mirror rows did not produce a
-- binding — investigate before flipping PublishToCore, do not proceed on a mismatch.

-- Drivers: linked mirror rows without a binding.
SELECT d."CompanyId", count(*) AS missing_driver_bindings
FROM "YandexDrivers" d
WHERE d."UserId" IS NOT NULL AND d."CompanyId" IS NOT NULL AND d."YaId" <> ''
  AND NOT EXISTS (SELECT 1 FROM "AggregatorDriverBindings" b
                  WHERE b."AggregatorId" = 0 AND b."CompanyId" = d."CompanyId"
                    AND b."AggregatorExternalId" = d."YaId")
GROUP BY d."CompanyId";

-- Cars: linked mirror rows without a binding.
SELECT c."CompanyId", count(*) AS missing_car_bindings
FROM "YandexCars" c
WHERE c."CarId" IS NOT NULL AND c."CompanyId" IS NOT NULL AND c."YaId" <> ''
  AND NOT EXISTS (SELECT 1 FROM "AggregatorCarBindings" b
                  WHERE b."AggregatorId" = 0 AND b."CompanyId" = c."CompanyId"
                    AND b."AggregatorExternalId" = c."YaId")
GROUP BY c."CompanyId";

-- Sanity: duplicate external ids inside one company would have violated the unique index, so a clean run
-- of the inserts above already proves there are none. This one reports mirror rows the backfill SKIPPED
-- (no UserId/CarId) — expected to be non-zero, listed so the number is known rather than assumed.
SELECT 'drivers_unlinked' AS what, count(*) FROM "YandexDrivers" WHERE "UserId" IS NULL
UNION ALL
SELECT 'cars_unlinked', count(*) FROM "YandexCars" WHERE "CarId" IS NULL;



START TRANSACTION;
ALTER TABLE "EmbeddingChunks" ADD "ContentHash" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260723164504_AddEmbeddingChunkContentHash', '10.0.1');

COMMIT;

rollback transaction