START TRANSACTION;
ALTER TABLE "UserCompanyGrants" DROP CONSTRAINT "FK_UserCompanyGrants_CompanyGrants_CompanyGrantId";

DROP INDEX "IX_UserCompanyGrants_CompanyGrantId";

ALTER TABLE "UserCompanyGrants" DROP COLUMN "CompanyGrantId";

ALTER TABLE "UserCompanyGrants" RENAME COLUMN "CompanyId" TO "AllowCompanyId";

ALTER TABLE "Users" ADD "LogDbEntryId" bigint;

ALTER TABLE "UserCompanyGrants" ADD "LogDbEntryId" bigint;

CREATE INDEX "IX_Users_LogDbEntryId" ON "Users" ("LogDbEntryId");

CREATE INDEX "IX_UserCompanyGrants_LogDbEntryId" ON "UserCompanyGrants" ("LogDbEntryId");

ALTER TABLE "UserCompanyGrants" ADD CONSTRAINT "FK_UserCompanyGrants_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id");

ALTER TABLE "Users" ADD CONSTRAINT "FK_Users_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260506182503_change_company_grants', '10.0.1');

COMMIT;



START TRANSACTION;
ALTER TABLE "Users" ADD "IsOfficeEmployee" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Users" ADD "IsPaymentLinkEmployee" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "OfficeOrders" ADD "PayerUserId" bigint;

ALTER TABLE "OfficeOrders" ADD "PaymentTaker" integer;

CREATE INDEX "IX_OfficeOrders_PayerUserId" ON "OfficeOrders" ("PayerUserId");

ALTER TABLE "OfficeOrders" ADD CONSTRAINT "FK_OfficeOrders_Users_PayerUserId" FOREIGN KEY ("PayerUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260511181651_AddOfficeOrderPaymentTaker', '10.0.1');

COMMIT;




START TRANSACTION;
CREATE TABLE "UserMessages" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" bigint NOT NULL,
    "CompanyId" bigint,
    "Title" text,
    "Body" text,
    "CompanyName" text,
    "IsRead" boolean NOT NULL,
    "ReadAt" timestamp with time zone,
    "Deleted" boolean NOT NULL,
    "CreatedTime" timestamp with time zone NOT NULL,
    "ModifiedTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_UserMessages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserMessages_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_UserMessages_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (103, '', 'User messages / read', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (104, '', 'User messages / send', 0);

CREATE INDEX "IX_UserMessages_CompanyId" ON "UserMessages" ("CompanyId");

CREATE INDEX "IX_UserMessages_UserId" ON "UserMessages" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260507170834_add_messages', '10.0.1');

COMMIT;


