START TRANSACTION;
ALTER TABLE "Purposes" ADD "IsSystem" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Purposes" ADD "Type" integer NOT NULL DEFAULT 1;

UPDATE "Purposes" SET "IsSystem" = true WHERE "PurposeReportTypeId" <> 0;

CREATE TABLE "DiscountApprovals" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "RentalId" bigint NOT NULL,
    "CompanyId" bigint NOT NULL,
    "RecommendedAmount" numeric(10,2) NOT NULL,
    "RequestedAmount" numeric(10,2) NOT NULL,
    "DiscountAmount" numeric(10,2) NOT NULL,
    "Status" integer NOT NULL,
    "RequestedById" bigint NOT NULL,
    "DecidedById" bigint,
    "DecidedAt" timestamp with time zone,
    "Comment" text,
    "Deleted" boolean NOT NULL,
    "CreatedTime" timestamp with time zone NOT NULL,
    "ModifiedTime" timestamp with time zone NOT NULL,
    "LogDbEntryId" bigint,
    CONSTRAINT "PK_DiscountApprovals" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DiscountApprovals_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_DiscountApprovals_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id"),
    CONSTRAINT "FK_DiscountApprovals_Rentals_RentalId" FOREIGN KEY ("RentalId") REFERENCES "Rentals" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_DiscountApprovals_Users_DecidedById" FOREIGN KEY ("DecidedById") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_DiscountApprovals_Users_RequestedById" FOREIGN KEY ("RequestedById") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "InspectionLinks" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "RentalId" bigint NOT NULL,
    "CompanyId" bigint NOT NULL,
    "Token" uuid NOT NULL,
    "Type" integer NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "RevokedAt" timestamp with time zone,
    "CreatedTime" timestamp with time zone NOT NULL,
    "ModifiedTime" timestamp with time zone NOT NULL,
    "CreatedById" bigint NOT NULL,
    "ModifiedById" bigint NOT NULL,
    "LogDbEntryId" bigint,
    CONSTRAINT "PK_InspectionLinks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InspectionLinks_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_InspectionLinks_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id"),
    CONSTRAINT "FK_InspectionLinks_Rentals_RentalId" FOREIGN KEY ("RentalId") REFERENCES "Rentals" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_InspectionLinks_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_InspectionLinks_Users_ModifiedById" FOREIGN KEY ("ModifiedById") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Inspections" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "RentalId" bigint NOT NULL,
    "CarId" bigint NOT NULL,
    "CompanyId" bigint NOT NULL,
    "Type" integer NOT NULL,
    "Description" text,
    "DamageAmount" numeric(10,2) NOT NULL,
    "Status" integer NOT NULL,
    "SavedAt" timestamp with time zone,
    "Deleted" boolean NOT NULL,
    "CreatedTime" timestamp with time zone NOT NULL,
    "ModifiedTime" timestamp with time zone NOT NULL,
    "LogDbEntryId" bigint,
    CONSTRAINT "PK_Inspections" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Inspections_Cars_CarId" FOREIGN KEY ("CarId") REFERENCES "Cars" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Inspections_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Inspections_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id"),
    CONSTRAINT "FK_Inspections_Rentals_RentalId" FOREIGN KEY ("RentalId") REFERENCES "Rentals" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "RentalDocuments" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "RentalId" bigint NOT NULL,
    "CompanyId" bigint NOT NULL,
    "Type" integer NOT NULL,
    "Status" integer NOT NULL,
    "Number" text,
    "UploadedFileId" uuid,
    "GeneratedAt" timestamp with time zone NOT NULL,
    "Deleted" boolean NOT NULL,
    "CreatedTime" timestamp with time zone NOT NULL,
    "ModifiedTime" timestamp with time zone NOT NULL,
    "CreatedById" bigint NOT NULL,
    "ModifiedById" bigint NOT NULL,
    "LogDbEntryId" bigint,
    CONSTRAINT "PK_RentalDocuments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RentalDocuments_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_RentalDocuments_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id"),
    CONSTRAINT "FK_RentalDocuments_Rentals_RentalId" FOREIGN KEY ("RentalId") REFERENCES "Rentals" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_RentalDocuments_UploadedFiles_UploadedFileId" FOREIGN KEY ("UploadedFileId") REFERENCES "UploadedFiles" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_RentalDocuments_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_RentalDocuments_Users_ModifiedById" FOREIGN KEY ("ModifiedById") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "RentalNotifications" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" bigint NOT NULL,
    "UserId" bigint NOT NULL,
    "Trigger" integer NOT NULL,
    "RentalId" bigint,
    "Message" text,
    "IsRead" boolean NOT NULL,
    "TriggerDay" date NOT NULL,
    "CreatedTime" timestamp with time zone NOT NULL,
    "ModifiedTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_RentalNotifications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RentalNotifications_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_RentalNotifications_Rentals_RentalId" FOREIGN KEY ("RentalId") REFERENCES "Rentals" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_RentalNotifications_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "RentalNotificationSettings" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" bigint NOT NULL,
    "Trigger" integer NOT NULL,
    "PushEnabled" boolean NOT NULL,
    "EmailEnabled" boolean NOT NULL,
    "TelegramEnabled" boolean NOT NULL,
    "CreatedTime" timestamp with time zone NOT NULL,
    "ModifiedTime" timestamp with time zone NOT NULL,
    "LogDbEntryId" bigint,
    CONSTRAINT "PK_RentalNotificationSettings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RentalNotificationSettings_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_RentalNotificationSettings_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id")
);

CREATE TABLE "Seasons" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" bigint NOT NULL,
    "Name" text NOT NULL,
    "StartDate" date NOT NULL,
    "EndDate" date NOT NULL,
    "IsPeak" boolean NOT NULL,
    "Deleted" boolean NOT NULL,
    "CreatedTime" timestamp with time zone NOT NULL,
    "ModifiedTime" timestamp with time zone NOT NULL,
    "LogDbEntryId" bigint,
    CONSTRAINT "PK_Seasons" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Seasons_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Seasons_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id")
);

CREATE TABLE "InspectionFiles" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "InspectionId" bigint NOT NULL,
    "UploadedFileId" uuid NOT NULL,
    "CreatedTime" timestamp with time zone NOT NULL,
    "ModifiedTime" timestamp with time zone NOT NULL,
    "LogDbEntryId" bigint,
    CONSTRAINT "PK_InspectionFiles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InspectionFiles_Inspections_InspectionId" FOREIGN KEY ("InspectionId") REFERENCES "Inspections" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_InspectionFiles_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id"),
    CONSTRAINT "FK_InspectionFiles_UploadedFiles_UploadedFileId" FOREIGN KEY ("UploadedFileId") REFERENCES "UploadedFiles" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "CarSeasonPrices" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CarId" bigint NOT NULL,
    "TierCode" integer NOT NULL,
    "SeasonId" bigint NOT NULL,
    "DailyRate" numeric(10,2) NOT NULL,
    "CreatedTime" timestamp with time zone NOT NULL,
    "ModifiedTime" timestamp with time zone NOT NULL,
    "LogDbEntryId" bigint,
    CONSTRAINT "PK_CarSeasonPrices" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_CarSeasonPrices_NonNegative" CHECK ("DailyRate" >= 0),
    CONSTRAINT "FK_CarSeasonPrices_Cars_CarId" FOREIGN KEY ("CarId") REFERENCES "Cars" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CarSeasonPrices_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id"),
    CONSTRAINT "FK_CarSeasonPrices_Seasons_SeasonId" FOREIGN KEY ("SeasonId") REFERENCES "Seasons" ("Id") ON DELETE RESTRICT
);

INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (180, '', 'Rent-a-Car P&L dashboard / read', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (181, '', 'Rent-a-Car customer report / read', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (182, '', 'Rent-a-Car documents / generate (contract, invoice)', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (183, '', 'Rent-a-Car inspections / read', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (184, '', 'Rent-a-Car inspections / manage (links, photos)', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (185, '', 'Rent-a-Car notification settings / manage', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (186, '', 'Rent-a-Car extension discount / approve', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (187, '', 'Rent-a-Car seasons / read', 0);

CREATE INDEX "IX_CarSeasonPrices_LogDbEntryId" ON "CarSeasonPrices" ("LogDbEntryId");

CREATE INDEX "IX_CarSeasonPrices_SeasonId" ON "CarSeasonPrices" ("SeasonId");

CREATE UNIQUE INDEX "UQ_CarSeasonPrices" ON "CarSeasonPrices" ("CarId", "TierCode", "SeasonId");

CREATE INDEX "IX_DiscountApprovals_CompanyId_Status" ON "DiscountApprovals" ("CompanyId", "Status");

CREATE INDEX "IX_DiscountApprovals_DecidedById" ON "DiscountApprovals" ("DecidedById");

CREATE INDEX "IX_DiscountApprovals_LogDbEntryId" ON "DiscountApprovals" ("LogDbEntryId");

CREATE INDEX "IX_DiscountApprovals_RentalId" ON "DiscountApprovals" ("RentalId");

CREATE INDEX "IX_DiscountApprovals_RequestedById" ON "DiscountApprovals" ("RequestedById");

CREATE INDEX "IX_InspectionFiles_InspectionId" ON "InspectionFiles" ("InspectionId");

CREATE INDEX "IX_InspectionFiles_LogDbEntryId" ON "InspectionFiles" ("LogDbEntryId");

CREATE INDEX "IX_InspectionFiles_UploadedFileId" ON "InspectionFiles" ("UploadedFileId");

CREATE INDEX "IX_InspectionLinks_CompanyId" ON "InspectionLinks" ("CompanyId");

CREATE INDEX "IX_InspectionLinks_CreatedById" ON "InspectionLinks" ("CreatedById");

CREATE INDEX "IX_InspectionLinks_LogDbEntryId" ON "InspectionLinks" ("LogDbEntryId");

CREATE INDEX "IX_InspectionLinks_ModifiedById" ON "InspectionLinks" ("ModifiedById");

CREATE INDEX "IX_InspectionLinks_RentalId" ON "InspectionLinks" ("RentalId");

CREATE UNIQUE INDEX "IX_InspectionLinks_Token" ON "InspectionLinks" ("Token");

CREATE INDEX "IX_Inspections_CarId" ON "Inspections" ("CarId");

CREATE INDEX "IX_Inspections_CompanyId_Type" ON "Inspections" ("CompanyId", "Type");

CREATE INDEX "IX_Inspections_LogDbEntryId" ON "Inspections" ("LogDbEntryId");

CREATE INDEX "IX_Inspections_RentalId" ON "Inspections" ("RentalId");

CREATE UNIQUE INDEX "UQ_Inspections_OpenDraft" ON "Inspections" ("RentalId", "Type") WHERE "SavedAt" IS NULL AND "Deleted" = false;

CREATE INDEX "IX_RentalDocuments_CompanyId_Type" ON "RentalDocuments" ("CompanyId", "Type");

CREATE INDEX "IX_RentalDocuments_CreatedById" ON "RentalDocuments" ("CreatedById");

CREATE INDEX "IX_RentalDocuments_LogDbEntryId" ON "RentalDocuments" ("LogDbEntryId");

CREATE INDEX "IX_RentalDocuments_ModifiedById" ON "RentalDocuments" ("ModifiedById");

CREATE INDEX "IX_RentalDocuments_RentalId" ON "RentalDocuments" ("RentalId");

CREATE INDEX "IX_RentalDocuments_UploadedFileId" ON "RentalDocuments" ("UploadedFileId");

CREATE UNIQUE INDEX "UQ_RentalDocuments_Company_Number" ON "RentalDocuments" ("CompanyId", "Number") WHERE "Number" <> '';

CREATE INDEX "IX_RentalNotifications_CompanyId" ON "RentalNotifications" ("CompanyId");

CREATE INDEX "IX_RentalNotifications_RentalId_Trigger_TriggerDay" ON "RentalNotifications" ("RentalId", "Trigger", "TriggerDay");

CREATE INDEX "IX_RentalNotifications_UserId_IsRead" ON "RentalNotifications" ("UserId", "IsRead");

CREATE INDEX "IX_RentalNotificationSettings_LogDbEntryId" ON "RentalNotificationSettings" ("LogDbEntryId");

CREATE UNIQUE INDEX "UQ_RentalNotificationSettings" ON "RentalNotificationSettings" ("CompanyId", "Trigger");

CREATE INDEX "IX_Seasons_CompanyId_StartDate" ON "Seasons" ("CompanyId", "StartDate");

CREATE INDEX "IX_Seasons_LogDbEntryId" ON "Seasons" ("LogDbEntryId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260709201019_RentokarV2Schema', '10.0.1');

COMMIT;

START TRANSACTION;
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (188, '', 'Rent-a-Car expense categories / manage', 0);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260710092219_AddRentCategoryManagePermission', '10.0.1');

COMMIT;

START TRANSACTION;
CREATE EXTENSION IF NOT EXISTS btree_gist;


                ALTER TABLE "Seasons" ADD CONSTRAINT "EX_Seasons_NoOverlap"
                EXCLUDE USING gist (
                    "CompanyId" WITH =,
                    daterange("StartDate", "EndDate", '[]') WITH &&
                ) WHERE ("Deleted" = false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260710092732_AddSeasonNoOverlapConstraint', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "DriverCarChanges" ADD "Confidence" integer NOT NULL DEFAULT 0;

ALTER TABLE "DriverCarChanges" ADD "LastSignalTime" timestamp with time zone;

ALTER TABLE "DriverCarChanges" ADD "LockedByUserId" bigint;

ALTER TABLE "DriverCarChanges" ADD "LockedUntil" timestamp with time zone;

ALTER TABLE "DriverCarChanges" ADD "Source" integer NOT NULL DEFAULT 0;

ALTER TABLE "DriverCarChanges" ADD "StartAnchored" boolean NOT NULL DEFAULT FALSE;

CREATE TABLE "CarDrivers" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" bigint NOT NULL,
    "CarId" bigint NOT NULL,
    "DriverId" bigint NOT NULL,
    "Active" boolean NOT NULL,
    "AutoAdded" boolean NOT NULL,
    "LogDbEntryId" bigint,
    CONSTRAINT "PK_CarDrivers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CarDrivers_Cars_CarId" FOREIGN KEY ("CarId") REFERENCES "Cars" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CarDrivers_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CarDrivers_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id"),
    CONSTRAINT "FK_CarDrivers_Users_DriverId" FOREIGN KEY ("DriverId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_DriverCarChanges_LockedByUserId" ON "DriverCarChanges" ("LockedByUserId");

CREATE INDEX "IX_CarDrivers_CarId" ON "CarDrivers" ("CarId");

CREATE UNIQUE INDEX "IX_CarDrivers_CarId_DriverId" ON "CarDrivers" ("CarId", "DriverId") WHERE "Active" = true;

CREATE INDEX "IX_CarDrivers_CompanyId" ON "CarDrivers" ("CompanyId");

CREATE INDEX "IX_CarDrivers_DriverId" ON "CarDrivers" ("DriverId");

CREATE INDEX "IX_CarDrivers_LogDbEntryId" ON "CarDrivers" ("LogDbEntryId");

ALTER TABLE "DriverCarChanges" ADD CONSTRAINT "FK_DriverCarChanges_Users_LockedByUserId" FOREIGN KEY ("LockedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT;


INSERT INTO "CarDrivers" ("CompanyId", "CarId", "DriverId", "Active", "AutoAdded")
SELECT DISTINCT u."CompanyId", u."CarId", u."Id", true, false
FROM "Users" u
WHERE u."CarId" IS NOT NULL AND u."CompanyId" IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM "CarDrivers" cd
    WHERE cd."CarId" = u."CarId" AND cd."DriverId" = u."Id" AND cd."Active");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260711154038_AddCarDriverRosterAndDrivingSignal', '10.0.1');

COMMIT;

START TRANSACTION;
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (189, '', 'Car driver / bind', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (190, '', 'Car driver / edit history', 0);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260711185315_SeedCarDriverPermissions', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "Purposes" ADD "PnlArticle" integer;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260711202920_AddPnlArticleToPurpose', '10.0.1');

COMMIT;

START TRANSACTION;
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (191, '', 'Salary / reopen paid document', 0);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260714164042_SeedSalaryReopenPermission', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "Cars" ADD "InvestorMonthlyIncome" numeric;

ALTER TABLE "Cars" ADD "IsInvestor" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260715060639_AddCarInvestorFields', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "DriverCarChanges" ADD "StartManuallyAnchored" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260715154315_AddStartManuallyAnchoredToDriverCarChange', '10.0.1');

COMMIT;

