START TRANSACTION;
ALTER TABLE "Transactions" ADD "PaymentStatus" integer;

CREATE TABLE "PaymentApprovals" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "TransactionId" bigint NOT NULL,
    "CompanyId" bigint NOT NULL,
    "Action" integer NOT NULL,
    "UserId" bigint NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL,
    "Comment" text,
    CONSTRAINT "PK_PaymentApprovals" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PaymentApprovals_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_PaymentApprovals_Transactions_TransactionId" FOREIGN KEY ("TransactionId") REFERENCES "Transactions" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PaymentApprovals_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (164, '', 'Payments / read', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (165, '', 'Payments / approve', 0);

CREATE INDEX "IX_Transactions_PaymentStatus" ON "Transactions" ("PaymentStatus");

CREATE INDEX "IX_PaymentApprovals_CompanyId" ON "PaymentApprovals" ("CompanyId");

CREATE INDEX "IX_PaymentApprovals_TransactionId" ON "PaymentApprovals" ("TransactionId");

CREATE INDEX "IX_PaymentApprovals_UserId" ON "PaymentApprovals" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260625130130_AddPaymentApprovalWorkflow', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "ChatMessages" ADD "IsFromBot" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260625160851_AddChatMessageIsFromBot', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "Transactions" ADD "LogDbEntryId" bigint;

CREATE INDEX "IX_Transactions_LogDbEntryId" ON "Transactions" ("LogDbEntryId");

ALTER TABLE "Transactions" ADD CONSTRAINT "FK_Transactions_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260625171836_AddTransactionAudit', '10.0.1');

COMMIT;

START TRANSACTION;
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (166, '', 'Transactions / edit', 0);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260625174011_AddTransactionEditPermission', '10.0.1');

COMMIT;

START TRANSACTION;
CREATE TABLE "FluidCheckPoints" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" bigint NOT NULL,
    "Name" text,
    "SortOrder" integer NOT NULL,
    "IsSystem" boolean NOT NULL,
    "Deleted" boolean NOT NULL,
    "LogDbEntryId" bigint,
    CONSTRAINT "PK_FluidCheckPoints" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_FluidCheckPoints_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_FluidCheckPoints_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id")
);

CREATE TABLE "InspectionSchedules" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" bigint NOT NULL,
    "VehicleId" bigint NOT NULL,
    "Mode" integer NOT NULL,
    "PeriodDays" integer,
    "AnchorDate" date,
    "EndDate" date,
    "Active" boolean NOT NULL,
    "Deleted" boolean NOT NULL,
    "CreatedTime" timestamp with time zone NOT NULL,
    "ModifiedTime" timestamp with time zone NOT NULL,
    "LogDbEntryId" bigint,
    CONSTRAINT "PK_InspectionSchedules" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InspectionSchedules_Cars_VehicleId" FOREIGN KEY ("VehicleId") REFERENCES "Cars" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_InspectionSchedules_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_InspectionSchedules_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id")
);

CREATE TABLE "InspectionZones" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" bigint NOT NULL,
    "Name" text,
    "Group" integer NOT NULL,
    "SortOrder" integer NOT NULL,
    "IsSystem" boolean NOT NULL,
    "Deleted" boolean NOT NULL,
    "LogDbEntryId" bigint,
    CONSTRAINT "PK_InspectionZones" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InspectionZones_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_InspectionZones_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id")
);

CREATE TABLE "InspectionScheduleDates" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" bigint NOT NULL,
    "ScheduleId" bigint NOT NULL,
    "Date" date NOT NULL,
    CONSTRAINT "PK_InspectionScheduleDates" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InspectionScheduleDates_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_InspectionScheduleDates_InspectionSchedules_ScheduleId" FOREIGN KEY ("ScheduleId") REFERENCES "InspectionSchedules" ("Id") ON DELETE CASCADE
);

CREATE TABLE "VehicleInspections" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" bigint NOT NULL,
    "VehicleId" bigint NOT NULL,
    "Type" integer NOT NULL,
    "Status" integer NOT NULL,
    "ScheduledDate" date NOT NULL,
    "RescheduledDate" date,
    "InspectedAt" timestamp with time zone,
    "MechanicId" bigint,
    "AssignedMechanicId" bigint,
    "ScheduleId" bigint,
    "Comment" text,
    "SentToService" boolean NOT NULL,
    "SentToServiceDate" date,
    "ReminderSentAt" timestamp with time zone,
    "OverdueNotifiedAt" timestamp with time zone,
    "Deleted" boolean NOT NULL,
    "CreatedTime" timestamp with time zone NOT NULL,
    "ModifiedTime" timestamp with time zone NOT NULL,
    "LogDbEntryId" bigint,
    CONSTRAINT "PK_VehicleInspections" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_VehicleInspections_Cars_VehicleId" FOREIGN KEY ("VehicleId") REFERENCES "Cars" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_VehicleInspections_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_VehicleInspections_InspectionSchedules_ScheduleId" FOREIGN KEY ("ScheduleId") REFERENCES "InspectionSchedules" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_VehicleInspections_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id"),
    CONSTRAINT "FK_VehicleInspections_Users_AssignedMechanicId" FOREIGN KEY ("AssignedMechanicId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_VehicleInspections_Users_MechanicId" FOREIGN KEY ("MechanicId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "InspectionFluidResults" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" bigint NOT NULL,
    "InspectionId" bigint NOT NULL,
    "FluidPointId" bigint NOT NULL,
    "Status" integer NOT NULL,
    "Comment" text,
    CONSTRAINT "PK_InspectionFluidResults" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InspectionFluidResults_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_InspectionFluidResults_FluidCheckPoints_FluidPointId" FOREIGN KEY ("FluidPointId") REFERENCES "FluidCheckPoints" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_InspectionFluidResults_VehicleInspections_InspectionId" FOREIGN KEY ("InspectionId") REFERENCES "VehicleInspections" ("Id") ON DELETE CASCADE
);

CREATE TABLE "InspectionUploadedFiles" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "InspectionId" bigint NOT NULL,
    "UploadedFileId" uuid NOT NULL,
    "PhotoType" integer NOT NULL,
    "CreatedTime" timestamp with time zone NOT NULL,
    "ModifiedTime" timestamp with time zone NOT NULL,
    "LogDbEntryId" bigint,
    CONSTRAINT "PK_InspectionUploadedFiles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InspectionUploadedFiles_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id"),
    CONSTRAINT "FK_InspectionUploadedFiles_UploadedFiles_UploadedFileId" FOREIGN KEY ("UploadedFileId") REFERENCES "UploadedFiles" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_InspectionUploadedFiles_VehicleInspections_InspectionId" FOREIGN KEY ("InspectionId") REFERENCES "VehicleInspections" ("Id") ON DELETE CASCADE
);

CREATE TABLE "InspectionZoneResults" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" bigint NOT NULL,
    "InspectionId" bigint NOT NULL,
    "ZoneId" bigint NOT NULL,
    "Status" integer NOT NULL,
    "Description" text,
    CONSTRAINT "PK_InspectionZoneResults" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InspectionZoneResults_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_InspectionZoneResults_InspectionZones_ZoneId" FOREIGN KEY ("ZoneId") REFERENCES "InspectionZones" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_InspectionZoneResults_VehicleInspections_InspectionId" FOREIGN KEY ("InspectionId") REFERENCES "VehicleInspections" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_FluidCheckPoints_CompanyId_Name" ON "FluidCheckPoints" ("CompanyId", "Name") WHERE "Deleted" = false;

CREATE INDEX "IX_FluidCheckPoints_LogDbEntryId" ON "FluidCheckPoints" ("LogDbEntryId");

CREATE INDEX "IX_InspectionFluidResults_CompanyId" ON "InspectionFluidResults" ("CompanyId");

CREATE INDEX "IX_InspectionFluidResults_FluidPointId" ON "InspectionFluidResults" ("FluidPointId");

CREATE INDEX "IX_InspectionFluidResults_InspectionId" ON "InspectionFluidResults" ("InspectionId");

CREATE INDEX "IX_InspectionScheduleDates_CompanyId" ON "InspectionScheduleDates" ("CompanyId");

CREATE INDEX "IX_InspectionScheduleDates_ScheduleId" ON "InspectionScheduleDates" ("ScheduleId");

CREATE INDEX "IX_InspectionSchedules_CompanyId" ON "InspectionSchedules" ("CompanyId");

CREATE INDEX "IX_InspectionSchedules_LogDbEntryId" ON "InspectionSchedules" ("LogDbEntryId");

CREATE INDEX "IX_InspectionSchedules_VehicleId" ON "InspectionSchedules" ("VehicleId");

CREATE INDEX "IX_InspectionUploadedFiles_InspectionId" ON "InspectionUploadedFiles" ("InspectionId");

CREATE INDEX "IX_InspectionUploadedFiles_LogDbEntryId" ON "InspectionUploadedFiles" ("LogDbEntryId");

CREATE INDEX "IX_InspectionUploadedFiles_UploadedFileId" ON "InspectionUploadedFiles" ("UploadedFileId");

CREATE INDEX "IX_InspectionZoneResults_CompanyId" ON "InspectionZoneResults" ("CompanyId");

CREATE INDEX "IX_InspectionZoneResults_InspectionId" ON "InspectionZoneResults" ("InspectionId");

CREATE INDEX "IX_InspectionZoneResults_ZoneId" ON "InspectionZoneResults" ("ZoneId");

CREATE UNIQUE INDEX "IX_InspectionZones_CompanyId_Name" ON "InspectionZones" ("CompanyId", "Name") WHERE "Deleted" = false;

CREATE INDEX "IX_InspectionZones_LogDbEntryId" ON "InspectionZones" ("LogDbEntryId");

CREATE INDEX "IX_VehicleInspections_AssignedMechanicId" ON "VehicleInspections" ("AssignedMechanicId");

CREATE INDEX "IX_VehicleInspections_CompanyId_VehicleId_ScheduledDate" ON "VehicleInspections" ("CompanyId", "VehicleId", "ScheduledDate");

CREATE INDEX "IX_VehicleInspections_LogDbEntryId" ON "VehicleInspections" ("LogDbEntryId");

CREATE INDEX "IX_VehicleInspections_MechanicId" ON "VehicleInspections" ("MechanicId");

CREATE INDEX "IX_VehicleInspections_ScheduleId" ON "VehicleInspections" ("ScheduleId");

CREATE INDEX "IX_VehicleInspections_VehicleId" ON "VehicleInspections" ("VehicleId");


                INSERT INTO "InspectionZones" ("CompanyId","Name","Group","SortOrder","IsSystem","Deleted")
                SELECT c."Id",'Hood',1,1,true,false FROM "Companies" c WHERE c."Deleted" = false;

                INSERT INTO "InspectionZones" ("CompanyId","Name","Group","SortOrder","IsSystem","Deleted")
                SELECT c."Id",'Roof',1,2,true,false FROM "Companies" c WHERE c."Deleted" = false;

                INSERT INTO "InspectionZones" ("CompanyId","Name","Group","SortOrder","IsSystem","Deleted")
                SELECT c."Id",'Front bumper',1,3,true,false FROM "Companies" c WHERE c."Deleted" = false;

                INSERT INTO "InspectionZones" ("CompanyId","Name","Group","SortOrder","IsSystem","Deleted")
                SELECT c."Id",'Rear bumper',1,4,true,false FROM "Companies" c WHERE c."Deleted" = false;

                INSERT INTO "InspectionZones" ("CompanyId","Name","Group","SortOrder","IsSystem","Deleted")
                SELECT c."Id",'Left side',1,5,true,false FROM "Companies" c WHERE c."Deleted" = false;

                INSERT INTO "InspectionZones" ("CompanyId","Name","Group","SortOrder","IsSystem","Deleted")
                SELECT c."Id",'Right side',1,6,true,false FROM "Companies" c WHERE c."Deleted" = false;

                INSERT INTO "InspectionZones" ("CompanyId","Name","Group","SortOrder","IsSystem","Deleted")
                SELECT c."Id",'Trunk lid',1,7,true,false FROM "Companies" c WHERE c."Deleted" = false;

                INSERT INTO "InspectionZones" ("CompanyId","Name","Group","SortOrder","IsSystem","Deleted")
                SELECT c."Id",'Interior',2,8,true,false FROM "Companies" c WHERE c."Deleted" = false;



                INSERT INTO "FluidCheckPoints" ("CompanyId","Name","SortOrder","IsSystem","Deleted")
                SELECT c."Id",'Engine oil',1,true,false FROM "Companies" c WHERE c."Deleted" = false;

                INSERT INTO "FluidCheckPoints" ("CompanyId","Name","SortOrder","IsSystem","Deleted")
                SELECT c."Id",'Coolant / antifreeze',2,true,false FROM "Companies" c WHERE c."Deleted" = false;

                INSERT INTO "FluidCheckPoints" ("CompanyId","Name","SortOrder","IsSystem","Deleted")
                SELECT c."Id",'Brake fluid',3,true,false FROM "Companies" c WHERE c."Deleted" = false;

                INSERT INTO "FluidCheckPoints" ("CompanyId","Name","SortOrder","IsSystem","Deleted")
                SELECT c."Id",'Power steering fluid',4,true,false FROM "Companies" c WHERE c."Deleted" = false;

                INSERT INTO "FluidCheckPoints" ("CompanyId","Name","SortOrder","IsSystem","Deleted")
                SELECT c."Id",'Washer fluid',5,true,false FROM "Companies" c WHERE c."Deleted" = false;

                INSERT INTO "FluidCheckPoints" ("CompanyId","Name","SortOrder","IsSystem","Deleted")
                SELECT c."Id",'Transmission fluid (ATF)',6,true,false FROM "Companies" c WHERE c."Deleted" = false;

                INSERT INTO "FluidCheckPoints" ("CompanyId","Name","SortOrder","IsSystem","Deleted")
                SELECT c."Id",'Clutch fluid',7,true,false FROM "Companies" c WHERE c."Deleted" = false;


INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260702172544_AddVehicleInspections', '10.0.1');

COMMIT;

START TRANSACTION;
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (167, '', 'Inspections / read', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (168, '', 'Inspections / create', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (169, '', 'Inspections / update', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (170, '', 'Inspections / delete', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (171, '', 'Inspections / manage schedule', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (172, '', 'Inspections / manage dictionaries', 0);

INSERT INTO "UserRoles" ("Id", "IsPorlalRole", "Name")
VALUES (14, TRUE, 'Mechanic');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260702173426_AddInspectionAccessAndMechanicRole', '10.0.1');

COMMIT;

START TRANSACTION;
CREATE TABLE "GnssAggregateHourlies" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" bigint NOT NULL,
    "UserId" bigint NOT NULL,
    "DeviceId" text,
    "HourBucket" timestamp with time zone NOT NULL,
    "SumCn0" double precision NOT NULL,
    "SumAgc" double precision NOT NULL,
    "SumSatellites" double precision NOT NULL,
    "MinCn0" double precision NOT NULL,
    "MaxCn0" double precision NOT NULL,
    "AnomalyCount" integer NOT NULL,
    "SamplesCount" integer NOT NULL,
    "GapCount" integer NOT NULL,
    "SumLat" double precision NOT NULL,
    "SumLng" double precision NOT NULL,
    CONSTRAINT "PK_GnssAggregateHourlies" PRIMARY KEY ("Id")
);

CREATE TABLE "GnssGeoBuckets" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" bigint NOT NULL,
    "Geohash7" text,
    "DayBucket" date NOT NULL,
    "SumCn0" double precision NOT NULL,
    "SamplesCount" integer NOT NULL,
    "AnomalyCount" integer NOT NULL,
    CONSTRAINT "PK_GnssGeoBuckets" PRIMARY KEY ("Id")
);

CREATE TABLE "GnssGeoWhitelists" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" bigint NOT NULL,
    "Name" text,
    "Polygon" jsonb,
    "Deleted" boolean NOT NULL,
    CONSTRAINT "PK_GnssGeoWhitelists" PRIMARY KEY ("Id")
);

CREATE TABLE "GnssIngestBatches" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "BatchId" text,
    "DeviceId" text,
    "UserId" bigint NOT NULL,
    "SamplesCount" integer NOT NULL,
    "ReceivedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_GnssIngestBatches" PRIMARY KEY ("Id")
);

CREATE TABLE "GnssThresholdsConfigHistories" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" bigint NOT NULL,
    "ConfigVersion" integer NOT NULL,
    "UpdatedByUserId" bigint NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "SnapshotJson" jsonb,
    CONSTRAINT "PK_GnssThresholdsConfigHistories" PRIMARY KEY ("Id")
);

CREATE TABLE "GnssThresholdsConfigs" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" bigint NOT NULL,
    "ConfigVersion" integer NOT NULL,
    "UpdatedAtUtc" timestamp with time zone NOT NULL,
    "SampleIntervalSeconds" integer NOT NULL,
    "ConfigRefreshIntervalSeconds" integer NOT NULL,
    "BatchUploadIntervalSeconds" integer NOT NULL,
    "EnabledJamming" boolean NOT NULL,
    "EnabledSpoofingAgcCn0" boolean NOT NULL,
    "EnabledSpoofingTime" boolean NOT NULL,
    "TopSatellitesForCn0Avg" integer NOT NULL,
    "JammingRecentEpochs" integer NOT NULL,
    "JammingBaselineEpochs" integer NOT NULL,
    "JammingMinCn0DropDbHz" double precision NOT NULL,
    "JammingMinAgcDropDb" double precision NOT NULL,
    "JammingRequireSimultaneous" boolean NOT NULL,
    "SpoofingRecentEpochs" integer NOT NULL,
    "SpoofingBaselineEpochs" integer NOT NULL,
    "SpoofingMinCn0RiseDbHz" double precision NOT NULL,
    "SpoofingMinAgcDropDb" double precision NOT NULL,
    "SpoofingRequireOppositeTrend" boolean NOT NULL,
    "SpoofingTimeMaxGnssNetworkDiffMs" bigint NOT NULL,
    "SpoofingTimeSkipIfUnsynced" boolean NOT NULL,
    "CapRequireAgcSupported" boolean NOT NULL,
    "CapMinBufferEpochs" integer NOT NULL,
    "CapMaxPendingSamples" integer NOT NULL,
    "CapMaxSamplesPerUpload" integer NOT NULL,
    "CapImmediateUploadCooldownSeconds" integer NOT NULL,
    CONSTRAINT "PK_GnssThresholdsConfigs" PRIMARY KEY ("Id")
);

INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (173, '', 'Mobile GNSS / read config', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (174, '', 'Mobile GNSS / write measurements', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (175, '', 'GPS integrity / read', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (176, '', 'GPS integrity / manage', 0);

CREATE UNIQUE INDEX "IX_GnssAggregateHourlies_DeviceId_HourBucket" ON "GnssAggregateHourlies" ("DeviceId", "HourBucket");

CREATE UNIQUE INDEX "IX_GnssGeoBuckets_Geohash7_DayBucket" ON "GnssGeoBuckets" ("Geohash7", "DayBucket");

CREATE UNIQUE INDEX "IX_GnssIngestBatches_BatchId" ON "GnssIngestBatches" ("BatchId");

CREATE UNIQUE INDEX "IX_GnssThresholdsConfigs_CompanyId" ON "GnssThresholdsConfigs" ("CompanyId");


CREATE SEQUENCE IF NOT EXISTS gnss_measurements_id_seq;

CREATE TABLE "gnss_measurements" (
    "Id" bigint NOT NULL DEFAULT nextval('gnss_measurements_id_seq'),
    "CompanyId" bigint NOT NULL,
    "UserId" bigint NOT NULL,
    "DeviceId" text NOT NULL,
    "BatchId" text NOT NULL,
    "CapturedAtUtc" timestamp with time zone NOT NULL,
    "ElapsedRealtimeNanos" bigint NOT NULL,
    "DataAvailable" boolean NOT NULL,
    "UnavailableReason" integer NULL,
    "NetworkTimeUtc" timestamp with time zone NULL,
    "NetworkTimeSynced" boolean NOT NULL,
    "GnssTimeUtcMs" bigint NULL,
    "HardwareClockDiscontinuityCount" integer NULL,
    "PrimaryAvgCn0DbHz" double precision NULL,
    "PrimaryAgcDb" double precision NULL,
    "PrimaryBandKey" text NULL,
    "VisibleSatelliteCount" integer NULL,
    "Latitude" double precision NULL,
    "Longitude" double precision NULL,
    "Geohash7" text NULL,
    "SpeedMps" double precision NULL,
    "BearingDeg" double precision NULL,
    "AccuracyM" double precision NULL,
    "AltitudeM" double precision NULL,
    "Provider" text NULL,
    "MeasurementsSupported" boolean NOT NULL,
    "AgcSupported" boolean NOT NULL,
    "GpsProviderEnabled" boolean NOT NULL,
    "IsFullTracking" boolean NULL,
    "ConfigVersion" integer NOT NULL,
    "UploadReason" integer NOT NULL,
    "IsAnomaly" boolean NOT NULL,
    "AnomalyType" integer NULL,
    "InWhitelistZone" boolean NOT NULL,
    "TimeSkewWarning" boolean NOT NULL,
    "Bands" jsonb NULL,
    "ReceivedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_gnss_measurements" PRIMARY KEY ("Id", "CapturedAtUtc")
) PARTITION BY RANGE ("CapturedAtUtc");

CREATE INDEX "IX_gnss_measurements_UserId_CapturedAtUtc"
    ON "gnss_measurements" ("UserId", "CapturedAtUtc");
CREATE INDEX "IX_gnss_measurements_DeviceId_CapturedAtUtc"
    ON "gnss_measurements" ("DeviceId", "CapturedAtUtc");
CREATE INDEX "IX_gnss_measurements_anomaly"
    ON "gnss_measurements" ("CapturedAtUtc") WHERE "IsAnomaly";

-- Create the current and next ISO-week partitions so ingest works immediately.
-- Deterministic-at-apply-time: computed from the ISO-week Monday of now() in UTC, so the boundary
-- matches GnssPartitionMaintenanceJob (which plans weeks from DateTime.UtcNow) regardless of the
-- DB session time zone — otherwise the two could disagree and the job would overlap a partition.
DO $$
DECLARE
    wk_start date := date_trunc('week', now() AT TIME ZONE 'UTC')::date;
    wk_next  date := wk_start + 7;
    wk_after date := wk_start + 14;
    p_curr   text := 'gnss_measurements_' || to_char(wk_start, 'IYYY_"w"IW');
    p_next   text := 'gnss_measurements_' || to_char(wk_next,  'IYYY_"w"IW');
BEGIN
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS %I PARTITION OF "gnss_measurements" FOR VALUES FROM (%L) TO (%L);',
        p_curr, wk_start::text, wk_next::text);
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS %I PARTITION OF "gnss_measurements" FOR VALUES FROM (%L) TO (%L);',
        p_next, wk_next::text, wk_after::text);
END $$;


INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260702184650_AddGnssMeasurements', '10.0.1');

COMMIT;

START TRANSACTION;
DROP INDEX "IX_GnssGeoBuckets_Geohash7_DayBucket";

DROP INDEX "IX_GnssAggregateHourlies_DeviceId_HourBucket";

ALTER TABLE "GnssAggregateHourlies" ALTER COLUMN "MinCn0" DROP NOT NULL;

ALTER TABLE "GnssAggregateHourlies" ALTER COLUMN "MaxCn0" DROP NOT NULL;

CREATE UNIQUE INDEX "IX_GnssGeoBuckets_CompanyId_Geohash7_DayBucket" ON "GnssGeoBuckets" ("CompanyId", "Geohash7", "DayBucket");

CREATE UNIQUE INDEX "IX_GnssAggregateHourlies_CompanyId_UserId_DeviceId_HourBucket" ON "GnssAggregateHourlies" ("CompanyId", "UserId", "DeviceId", "HourBucket");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260703185807_FixGnssAggregateTenantKeysAndNullableCn0', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "Orders" ADD "DropoffLatitude" numeric;

ALTER TABLE "Orders" ADD "DropoffLongitude" numeric;

ALTER TABLE "Orders" ADD "PickupLatitude" numeric;

ALTER TABLE "Orders" ADD "PickupLongitude" numeric;

ALTER TABLE "Orders" ADD "Rating" numeric;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260703203426_AddOrderRouteAndRating', '10.0.1');

COMMIT;

START TRANSACTION;
CREATE TABLE "OrderTrackPoints" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" bigint NOT NULL,
    "OrderId" bigint NOT NULL,
    "TrackedAt" timestamp with time zone NOT NULL,
    "Lat" double precision NOT NULL,
    "Lon" double precision NOT NULL,
    "Speed" double precision NOT NULL,
    "OrderStatus" integer NOT NULL,
    "Direction" integer,
    "DistanceM" double precision,
    CONSTRAINT "PK_OrderTrackPoints" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrderTrackPoints_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_OrderTrackPoints_CompanyId" ON "OrderTrackPoints" ("CompanyId");

CREATE UNIQUE INDEX "IX_OrderTrackPoints_OrderId_TrackedAt" ON "OrderTrackPoints" ("OrderId", "TrackedAt");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260703214014_AddOrderTrackPoints', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "YandexOrders" ADD "NextTrackAttemptAt" timestamp with time zone;

ALTER TABLE "YandexOrders" ADD "TrackAttempts" integer NOT NULL DEFAULT 0;

ALTER TABLE "YandexOrders" ADD "TrackFetchedAt" timestamp with time zone;

ALTER TABLE "YandexOrders" ADD "TrackStatus" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260703214659_AddYandexOrderTrackFields', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "Companies" ADD "YangoTrackOrdersEnabled" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260704054956_AddCompanyYangoTrackOrdersEnabled', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "Companies" ADD "GoogleMapsApiKey" text;

ALTER TABLE "Companies" ADD "MapProvider" integer NOT NULL DEFAULT 0;

ALTER TABLE "Companies" ADD "MapTilerKey" text;

ALTER TABLE "Companies" ADD "OrsApiKey" text;

ALTER TABLE "Companies" ADD "OrsBaseUrl" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260704115419_AddMapKeysToCompany', '10.0.1');

COMMIT;

  GRANT CREATE ON SCHEMA public TO limousine;
  ALTER TABLE gnss_measurements          OWNER TO limousine;
  ALTER TABLE gnss_measurements_2026_w27 OWNER TO limousine;
  ALTER TABLE gnss_measurements_2026_w28 OWNER TO limousine;

  ALTER SEQUENCE gnss_measurements_id_seq OWNER TO limousine;
