START TRANSACTION;
CREATE TABLE "TaskBoards" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" bigint NOT NULL,
    "TaskTypeId" integer NOT NULL,
    "Name" text,
    "Deleted" boolean NOT NULL,
    "CreatedTime" timestamp with time zone NOT NULL,
    "ModifiedTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TaskBoards" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TaskBoards_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TaskBoardColumns" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "TaskBoardId" bigint NOT NULL,
    "Name" text,
    "SortOrder" integer NOT NULL,
    "IsDefault" boolean NOT NULL,
    "IsDoneColumn" boolean NOT NULL,
    "Deleted" boolean NOT NULL,
    "CreatedTime" timestamp with time zone NOT NULL,
    "ModifiedTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TaskBoardColumns" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TaskBoardColumns_TaskBoards_TaskBoardId" FOREIGN KEY ("TaskBoardId") REFERENCES "TaskBoards" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TaskRecurrences" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" bigint NOT NULL,
    "TaskBoardId" bigint NOT NULL,
    "Title" text,
    "Description" text,
    "Priority" integer NOT NULL,
    "DueDaysOffset" integer NOT NULL,
    "CronSchedule" text,
    "Enabled" boolean NOT NULL,
    "CreatedUserId" bigint NOT NULL,
    "LastTriggeredTime" timestamp with time zone,
    "Deleted" boolean NOT NULL,
    "CreatedTime" timestamp with time zone NOT NULL,
    "ModifiedTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TaskRecurrences" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TaskRecurrences_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TaskRecurrences_TaskBoards_TaskBoardId" FOREIGN KEY ("TaskBoardId") REFERENCES "TaskBoards" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TaskRecurrences_Users_CreatedUserId" FOREIGN KEY ("CreatedUserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TaskItems" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" bigint NOT NULL,
    "TaskBoardId" bigint NOT NULL,
    "TaskBoardColumnId" bigint NOT NULL,
    "Title" text,
    "Description" text,
    "Priority" integer NOT NULL,
    "Status" integer NOT NULL,
    "DueDate" timestamp with time zone,
    "CompletedDate" timestamp with time zone,
    "CreatedUserId" bigint NOT NULL,
    "RelatedCarId" bigint,
    "RelatedDriverId" bigint,
    "RecurrenceId" bigint,
    "SortOrder" integer NOT NULL,
    "Deleted" boolean NOT NULL,
    "CreatedTime" timestamp with time zone NOT NULL,
    "ModifiedTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TaskItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TaskItems_Cars_RelatedCarId" FOREIGN KEY ("RelatedCarId") REFERENCES "Cars" ("Id"),
    CONSTRAINT "FK_TaskItems_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TaskItems_TaskBoardColumns_TaskBoardColumnId" FOREIGN KEY ("TaskBoardColumnId") REFERENCES "TaskBoardColumns" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TaskItems_TaskBoards_TaskBoardId" FOREIGN KEY ("TaskBoardId") REFERENCES "TaskBoards" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TaskItems_TaskRecurrences_RecurrenceId" FOREIGN KEY ("RecurrenceId") REFERENCES "TaskRecurrences" ("Id"),
    CONSTRAINT "FK_TaskItems_Users_CreatedUserId" FOREIGN KEY ("CreatedUserId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TaskItems_Users_RelatedDriverId" FOREIGN KEY ("RelatedDriverId") REFERENCES "Users" ("Id")
);

CREATE TABLE "TaskRecurrenceAssignees" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "TaskRecurrenceId" bigint NOT NULL,
    "UserId" bigint NOT NULL,
    CONSTRAINT "PK_TaskRecurrenceAssignees" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TaskRecurrenceAssignees_TaskRecurrences_TaskRecurrenceId" FOREIGN KEY ("TaskRecurrenceId") REFERENCES "TaskRecurrences" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TaskRecurrenceAssignees_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TaskAssignees" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "TaskItemId" bigint NOT NULL,
    "UserId" bigint NOT NULL,
    "AssignedTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TaskAssignees" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TaskAssignees_TaskItems_TaskItemId" FOREIGN KEY ("TaskItemId") REFERENCES "TaskItems" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TaskAssignees_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TaskAttachments" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "TaskItemId" bigint NOT NULL,
    "UploadedFileId" uuid NOT NULL,
    CONSTRAINT "PK_TaskAttachments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TaskAttachments_TaskItems_TaskItemId" FOREIGN KEY ("TaskItemId") REFERENCES "TaskItems" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TaskAttachments_UploadedFiles_UploadedFileId" FOREIGN KEY ("UploadedFileId") REFERENCES "UploadedFiles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TaskComments" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "TaskItemId" bigint NOT NULL,
    "UserId" bigint NOT NULL,
    "Text" text,
    "IsDeleted" boolean NOT NULL,
    "CreatedTime" timestamp with time zone NOT NULL,
    "ModifiedTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TaskComments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TaskComments_TaskItems_TaskItemId" FOREIGN KEY ("TaskItemId") REFERENCES "TaskItems" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TaskComments_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TaskNotifications" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" bigint NOT NULL,
    "UserId" bigint NOT NULL,
    "TaskItemId" bigint NOT NULL,
    "Message" text,
    "NotificationType" integer NOT NULL,
    "IsRead" boolean NOT NULL,
    "CreatedTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TaskNotifications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TaskNotifications_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TaskNotifications_TaskItems_TaskItemId" FOREIGN KEY ("TaskItemId") REFERENCES "TaskItems" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TaskNotifications_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (67, '', 'Tasks / read', 0),
       (68, '', 'Tasks / create', 0),
       (69, '', 'Tasks / change', 0),
       (70, '', 'Tasks / delete', 0),
       (71, '', 'Tasks / complete', 0),
       (72, '', 'Tasks / manage board', 0),
       (73, '', 'Tasks / manage recurrence', 0)
ON CONFLICT ("Id") DO NOTHING;

INSERT INTO "UserRoles" ("Id", "IsPorlalRole", "Name")
VALUES (8, true, 'Marketing'),
       (9, true, 'IT')
ON CONFLICT ("Id") DO NOTHING;

CREATE INDEX "IX_TaskAssignees_TaskItemId" ON "TaskAssignees" ("TaskItemId");

CREATE INDEX "IX_TaskAssignees_UserId" ON "TaskAssignees" ("UserId");

CREATE INDEX "IX_TaskAttachments_TaskItemId" ON "TaskAttachments" ("TaskItemId");

CREATE INDEX "IX_TaskAttachments_UploadedFileId" ON "TaskAttachments" ("UploadedFileId");

CREATE INDEX "IX_TaskBoardColumns_TaskBoardId" ON "TaskBoardColumns" ("TaskBoardId");

CREATE INDEX "IX_TaskBoards_CompanyId" ON "TaskBoards" ("CompanyId");

CREATE INDEX "IX_TaskComments_TaskItemId" ON "TaskComments" ("TaskItemId");

CREATE INDEX "IX_TaskComments_UserId" ON "TaskComments" ("UserId");

CREATE INDEX "IX_TaskItems_CompanyId" ON "TaskItems" ("CompanyId");

CREATE INDEX "IX_TaskItems_CreatedUserId" ON "TaskItems" ("CreatedUserId");

CREATE INDEX "IX_TaskItems_RecurrenceId" ON "TaskItems" ("RecurrenceId");

CREATE INDEX "IX_TaskItems_RelatedCarId" ON "TaskItems" ("RelatedCarId");

CREATE INDEX "IX_TaskItems_RelatedDriverId" ON "TaskItems" ("RelatedDriverId");

CREATE INDEX "IX_TaskItems_TaskBoardColumnId" ON "TaskItems" ("TaskBoardColumnId");

CREATE INDEX "IX_TaskItems_TaskBoardId" ON "TaskItems" ("TaskBoardId");

CREATE INDEX "IX_TaskNotifications_CompanyId" ON "TaskNotifications" ("CompanyId");

CREATE INDEX "IX_TaskNotifications_TaskItemId" ON "TaskNotifications" ("TaskItemId");

CREATE INDEX "IX_TaskNotifications_UserId" ON "TaskNotifications" ("UserId");

CREATE INDEX "IX_TaskRecurrenceAssignees_TaskRecurrenceId" ON "TaskRecurrenceAssignees" ("TaskRecurrenceId");

CREATE INDEX "IX_TaskRecurrenceAssignees_UserId" ON "TaskRecurrenceAssignees" ("UserId");

CREATE INDEX "IX_TaskRecurrences_CompanyId" ON "TaskRecurrences" ("CompanyId");

CREATE INDEX "IX_TaskRecurrences_CreatedUserId" ON "TaskRecurrences" ("CreatedUserId");

CREATE INDEX "IX_TaskRecurrences_TaskBoardId" ON "TaskRecurrences" ("TaskBoardId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260225190218_AddTaskManagement', '10.0.1');

COMMIT;

START TRANSACTION;
CREATE TABLE "TaskTeams" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" bigint NOT NULL,
    "Name" text,
    "Description" text,
    "Color" text,
    "Deleted" boolean NOT NULL,
    "CreatedTime" timestamp with time zone NOT NULL,
    "ModifiedTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TaskTeams" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TaskTeams_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_TaskTeams_CompanyId" ON "TaskTeams" ("CompanyId");

CREATE TABLE "TaskTeamMembers" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "TaskTeamId" bigint NOT NULL,
    "UserId" bigint NOT NULL,
    "Role" integer NOT NULL,
    "Deleted" boolean NOT NULL,
    "CreatedTime" timestamp with time zone NOT NULL,
    "ModifiedTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TaskTeamMembers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TaskTeamMembers_TaskTeams_TaskTeamId" FOREIGN KEY ("TaskTeamId") REFERENCES "TaskTeams" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TaskTeamMembers_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_TaskTeamMembers_TaskTeamId" ON "TaskTeamMembers" ("TaskTeamId");

CREATE INDEX "IX_TaskTeamMembers_UserId" ON "TaskTeamMembers" ("UserId");

ALTER TABLE "TaskBoards" ADD "Description" text;

ALTER TABLE "TaskBoards" ADD "TeamId" bigint;


                INSERT INTO "TaskTeams" ("CompanyId", "Name", "Description", "Color", "Deleted", "CreatedTime", "ModifiedTime")
                SELECT DISTINCT "CompanyId", 'General', 'Migrated from legacy boards', '#4A90D9', false, NOW(), NOW()
                FROM "TaskBoards"
                WHERE "Deleted" = false;

                UPDATE "TaskBoards" b
                SET "TeamId" = t."Id"
                FROM "TaskTeams" t
                WHERE t."CompanyId" = b."CompanyId" AND t."Name" = 'General';

                INSERT INTO "TaskTeamMembers" ("TaskTeamId", "UserId", "Role", "Deleted", "CreatedTime", "ModifiedTime")
                SELECT DISTINCT t."Id", u."Id", 0, false, NOW(), NOW()
                FROM "TaskTeams" t
                JOIN "Users" u ON u."CompanyId" = t."CompanyId" AND u."Role" IN (0, 6)
                WHERE t."Name" = 'General';


UPDATE "TaskBoards" SET "TeamId" = 0 WHERE "TeamId" IS NULL;
ALTER TABLE "TaskBoards" ALTER COLUMN "TeamId" SET NOT NULL;
ALTER TABLE "TaskBoards" ALTER COLUMN "TeamId" SET DEFAULT 0;

ALTER TABLE "TaskBoards" DROP COLUMN "TaskTypeId";

CREATE TABLE "TaskBoardFavorites" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" bigint NOT NULL,
    "TaskBoardId" bigint NOT NULL,
    "CreatedTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TaskBoardFavorites" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TaskBoardFavorites_TaskBoards_TaskBoardId" FOREIGN KEY ("TaskBoardId") REFERENCES "TaskBoards" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TaskBoardFavorites_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_TaskBoardFavorites_TaskBoardId" ON "TaskBoardFavorites" ("TaskBoardId");

CREATE UNIQUE INDEX "IX_TaskBoardFavorites_UserId_TaskBoardId" ON "TaskBoardFavorites" ("UserId", "TaskBoardId");

CREATE INDEX "IX_TaskBoards_TeamId" ON "TaskBoards" ("TeamId");

ALTER TABLE "TaskBoards" ADD CONSTRAINT "FK_TaskBoards_TaskTeams_TeamId" FOREIGN KEY ("TeamId") REFERENCES "TaskTeams" ("Id") ON DELETE CASCADE;

INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (74, '', 'Tasks / manage teams', 0);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260227081747_MigrateTaskBoardsToTeams', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "TaskBoards" ADD "AllowReassignment" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "TaskBoards" ADD "VisibilityMode" integer NOT NULL DEFAULT 0;

ALTER TABLE "TaskBoardColumns" ADD "IsCancelledColumn" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "TaskBoardColumns" ADD "WipLimit" integer;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260227170853_AddBoardSettings', '10.0.1');

COMMIT;

START TRANSACTION;
CREATE TABLE "TaskLabels" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" bigint NOT NULL,
    "Name" text,
    "Color" text,
    "SortOrder" integer NOT NULL,
    "IsSystem" boolean NOT NULL,
    "Deleted" boolean NOT NULL,
    "CreatedTime" timestamp with time zone NOT NULL,
    "ModifiedTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TaskLabels" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TaskLabels_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TaskItemLabels" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "TaskItemId" bigint NOT NULL,
    "TaskLabelId" bigint NOT NULL,
    CONSTRAINT "PK_TaskItemLabels" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TaskItemLabels_TaskItems_TaskItemId" FOREIGN KEY ("TaskItemId") REFERENCES "TaskItems" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TaskItemLabels_TaskLabels_TaskLabelId" FOREIGN KEY ("TaskLabelId") REFERENCES "TaskLabels" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_TaskItemLabels_TaskItemId" ON "TaskItemLabels" ("TaskItemId");

CREATE INDEX "IX_TaskItemLabels_TaskLabelId" ON "TaskItemLabels" ("TaskLabelId");

CREATE INDEX "IX_TaskLabels_CompanyId" ON "TaskLabels" ("CompanyId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260227171718_AddTaskLabels', '10.0.1');

COMMIT;

START TRANSACTION;
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260227173830_UpdateTaskPriority', '10.0.1');

COMMIT;

START TRANSACTION;

                UPDATE "TaskItems" SET "Priority" = CASE
                    WHEN "Priority" = 3 THEN 5
                    WHEN "Priority" = 2 THEN 3
                    WHEN "Priority" = 1 THEN 2
                    WHEN "Priority" = 0 THEN 1
                    WHEN "Priority" = -1 THEN 0
                    ELSE 0
                END;
                UPDATE "TaskRecurrences" SET "Priority" = CASE
                    WHEN "Priority" = 3 THEN 5
                    WHEN "Priority" = 2 THEN 3
                    WHEN "Priority" = 1 THEN 2
                    WHEN "Priority" = 0 THEN 1
                    WHEN "Priority" = -1 THEN 0
                    ELSE 0
                END;


INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260228150651_RemapTaskPriority', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "TaskItems" ADD "RelatedOrderId" bigint;

CREATE INDEX "IX_TaskItems_RelatedOrderId" ON "TaskItems" ("RelatedOrderId");

ALTER TABLE "TaskItems" ADD CONSTRAINT "FK_TaskItems_Orders_RelatedOrderId" FOREIGN KEY ("RelatedOrderId") REFERENCES "Orders" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260228183700_AddRelatedOrderToTaskItem', '10.0.1');

COMMIT;




START TRANSACTION;
INSERT INTO "TaskLabels" ("Id", "Color", "CompanyId", "CreatedTime", "Deleted", "IsSystem", "ModifiedTime", "Name", "SortOrder")
VALUES (1, '#3B82F6', 1, TIMESTAMPTZ '2026-03-01T00:00:00Z', FALSE, TRUE, TIMESTAMPTZ '2026-03-01T00:00:00Z', 'Repair', 1);
INSERT INTO "TaskLabels" ("Id", "Color", "CompanyId", "CreatedTime", "Deleted", "IsSystem", "ModifiedTime", "Name", "SortOrder")
VALUES (2, '#EF4444', 1, TIMESTAMPTZ '2026-03-01T00:00:00Z', FALSE, TRUE, TIMESTAMPTZ '2026-03-01T00:00:00Z', 'Illegal trip', 2);
INSERT INTO "TaskLabels" ("Id", "Color", "CompanyId", "CreatedTime", "Deleted", "IsSystem", "ModifiedTime", "Name", "SortOrder")
VALUES (3, '#8B5CF6', 1, TIMESTAMPTZ '2026-03-01T00:00:00Z', FALSE, TRUE, TIMESTAMPTZ '2026-03-01T00:00:00Z', 'Driver change', 3);
INSERT INTO "TaskLabels" ("Id", "Color", "CompanyId", "CreatedTime", "Deleted", "IsSystem", "ModifiedTime", "Name", "SortOrder")
VALUES (4, '#F59E0B', 1, TIMESTAMPTZ '2026-03-01T00:00:00Z', FALSE, TRUE, TIMESTAMPTZ '2026-03-01T00:00:00Z', 'Debt', 4);
INSERT INTO "TaskLabels" ("Id", "Color", "CompanyId", "CreatedTime", "Deleted", "IsSystem", "ModifiedTime", "Name", "SortOrder")
VALUES (5, '#10B981', 1, TIMESTAMPTZ '2026-03-01T00:00:00Z', FALSE, TRUE, TIMESTAMPTZ '2026-03-01T00:00:00Z', 'Car issuance', 5);
INSERT INTO "TaskLabels" ("Id", "Color", "CompanyId", "CreatedTime", "Deleted", "IsSystem", "ModifiedTime", "Name", "SortOrder")
VALUES (6, '#06B6D4', 1, TIMESTAMPTZ '2026-03-01T00:00:00Z', FALSE, TRUE, TIMESTAMPTZ '2026-03-01T00:00:00Z', 'Car acceptance', 6);
INSERT INTO "TaskLabels" ("Id", "Color", "CompanyId", "CreatedTime", "Deleted", "IsSystem", "ModifiedTime", "Name", "SortOrder")
VALUES (7, '#6366F1', 1, TIMESTAMPTZ '2026-03-01T00:00:00Z', FALSE, TRUE, TIMESTAMPTZ '2026-03-01T00:00:00Z', 'Document control', 7);
INSERT INTO "TaskLabels" ("Id", "Color", "CompanyId", "CreatedTime", "Deleted", "IsSystem", "ModifiedTime", "Name", "SortOrder")
VALUES (8, '#EC4899', 1, TIMESTAMPTZ '2026-03-01T00:00:00Z', FALSE, TRUE, TIMESTAMPTZ '2026-03-01T00:00:00Z', 'Mileage control', 8);
INSERT INTO "TaskLabels" ("Id", "Color", "CompanyId", "CreatedTime", "Deleted", "IsSystem", "ModifiedTime", "Name", "SortOrder")
VALUES (9, '#F97316', 1, TIMESTAMPTZ '2026-03-01T00:00:00Z', FALSE, TRUE, TIMESTAMPTZ '2026-03-01T00:00:00Z', 'Technical support', 9);

SELECT setval(
    pg_get_serial_sequence('"TaskLabels"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "TaskLabels") + 1,
        nextval(pg_get_serial_sequence('"TaskLabels"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260301193828_SeedTaskLabels', '10.0.1');

COMMIT;




START TRANSACTION;
CREATE TABLE "UserNotificationPreferences" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" bigint NOT NULL,
    "CompanyId" bigint NOT NULL,
    "EmailEnabled" boolean NOT NULL,
    "CreatedTime" timestamp with time zone NOT NULL,
    "ModifiedTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_UserNotificationPreferences" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserNotificationPreferences_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserNotificationPreferences_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (75, '', 'Tasks / manage automation', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (76, '', 'Tasks / view dashboard', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (77, '', 'Tasks / view audit', 0);

CREATE INDEX "IX_UserNotificationPreferences_CompanyId" ON "UserNotificationPreferences" ("CompanyId");

CREATE INDEX "IX_UserNotificationPreferences_UserId" ON "UserNotificationPreferences" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260312213037_AddNotificationPrefsAndNewPermissions', '10.0.1');

COMMIT;

START TRANSACTION;
CREATE TABLE "TaskAutomationRules" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" bigint NOT NULL,
    "Name" text,
    "EventTriggerType" integer NOT NULL,
    "TargetBoardId" bigint NOT NULL,
    "TargetColumnId" bigint,
    "TitleTemplate" text,
    "DescriptionTemplate" text,
    "Priority" integer NOT NULL,
    "DueDaysOffset" integer NOT NULL,
    "AutoAssign" boolean NOT NULL,
    "Enabled" boolean NOT NULL,
    "Deleted" boolean NOT NULL,
    "CreatedUserId" bigint NOT NULL,
    "CreatedTime" timestamp with time zone NOT NULL,
    "ModifiedTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TaskAutomationRules" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TaskAutomationRules_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TaskAutomationRules_TaskBoardColumns_TargetColumnId" FOREIGN KEY ("TargetColumnId") REFERENCES "TaskBoardColumns" ("Id"),
    CONSTRAINT "FK_TaskAutomationRules_TaskBoards_TargetBoardId" FOREIGN KEY ("TargetBoardId") REFERENCES "TaskBoards" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TaskAutomationRules_Users_CreatedUserId" FOREIGN KEY ("CreatedUserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TaskAutomationRuleLabels" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "RuleId" bigint NOT NULL,
    "LabelId" bigint NOT NULL,
    CONSTRAINT "PK_TaskAutomationRuleLabels" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TaskAutomationRuleLabels_TaskAutomationRules_RuleId" FOREIGN KEY ("RuleId") REFERENCES "TaskAutomationRules" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TaskAutomationRuleLabels_TaskLabels_LabelId" FOREIGN KEY ("LabelId") REFERENCES "TaskLabels" ("Id") ON DELETE CASCADE
);

INSERT INTO "EventTriggers" ("Id", "Name")
VALUES (9, 'Illegal trip');
INSERT INTO "EventTriggers" ("Id", "Name")
VALUES (10, 'Low cost per km');
INSERT INTO "EventTriggers" ("Id", "Name")
VALUES (11, 'Missed shift');
INSERT INTO "EventTriggers" ("Id", "Name")
VALUES (12, 'No show office');

CREATE INDEX "IX_TaskAutomationRuleLabels_LabelId" ON "TaskAutomationRuleLabels" ("LabelId");

CREATE INDEX "IX_TaskAutomationRuleLabels_RuleId" ON "TaskAutomationRuleLabels" ("RuleId");

CREATE INDEX "IX_TaskAutomationRules_CompanyId" ON "TaskAutomationRules" ("CompanyId");

CREATE INDEX "IX_TaskAutomationRules_CreatedUserId" ON "TaskAutomationRules" ("CreatedUserId");

CREATE INDEX "IX_TaskAutomationRules_TargetBoardId" ON "TaskAutomationRules" ("TargetBoardId");

CREATE INDEX "IX_TaskAutomationRules_TargetColumnId" ON "TaskAutomationRules" ("TargetColumnId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260312215243_AddTaskAutomation', '10.0.1');

COMMIT;

START TRANSACTION;
CREATE TABLE "AuditLogs" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "EntityName" text,
    "EntityId" bigint NOT NULL,
    "Action" text,
    "UserId" bigint,
    "CompanyId" bigint NOT NULL,
    "OldValues" text,
    "NewValues" text,
    "CreatedTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260313091646_AddAuditLog', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "TaskItems" ADD "DueDateOffsetDays" integer;

ALTER TABLE "TaskItems" ADD "IsTemplate" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260313091830_AddTaskTemplateFields', '10.0.1');

COMMIT;

START TRANSACTION;
DROP INDEX "IX_TaskAssignees_TaskItemId";

CREATE UNIQUE INDEX "IX_TaskAssignees_TaskItemId_UserId" ON "TaskAssignees" ("TaskItemId", "UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260313194047_AddUniqueIndexTaskAssignee', '10.0.1');

COMMIT;

START TRANSACTION;

                DELETE FROM "TaskTeamMembers" tm
                USING "Users" u
                WHERE tm."UserId" = u."Id" AND u."Role" IN (0, 6);



                INSERT INTO "TaskTeamMembers" ("TaskTeamId", "UserId", "Role", "Deleted", "CreatedTime", "ModifiedTime")
                SELECT t."Id", u."Id", 0, false, NOW(), NOW()
                FROM "TaskTeams" t
                JOIN "Users" u ON u."CompanyId" = t."CompanyId" AND u."Role" IN (1, 4)
                WHERE NOT EXISTS (
                    SELECT 1 FROM "TaskTeamMembers" existing
                    WHERE existing."TaskTeamId" = t."Id"
                      AND existing."UserId" = u."Id"
                      AND existing."Deleted" = false
                );


INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260317114628_FixTeamMemberSeeding', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "TaskItems" ADD "RelatedRepairOrderId" bigint;

CREATE INDEX "IX_TaskItems_RelatedRepairOrderId" ON "TaskItems" ("RelatedRepairOrderId");

ALTER TABLE "TaskItems" ADD CONSTRAINT "FK_TaskItems_RepairOrders_RelatedRepairOrderId" FOREIGN KEY ("RelatedRepairOrderId") REFERENCES "RepairOrders" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260317122057_AddRelatedRepairOrderToTask', '10.0.1');

COMMIT;



START TRANSACTION;
INSERT INTO "AuthAccesses" ("Id", "Name", "Description", "Priority")
VALUES (75, 'Tasks / manage automation', '', 0),
       (76, 'Tasks / view dashboard', '', 0),
       (77, 'Tasks / view audit', '', 0)
ON CONFLICT ("Id") DO UPDATE SET "Name" = EXCLUDED."Name";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260328093744_AddMissingTaskPermissions', '10.0.1');

COMMIT;


START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260412183228_add_TaskAccesses', '10.0.1');

COMMIT;


START TRANSACTION;
DROP TABLE "AuditLogs";

ALTER TABLE "TaskTeams" ADD "LogDbEntryId" bigint;

ALTER TABLE "TaskItems" ADD "LogDbEntryId" bigint;

ALTER TABLE "TaskBoards" ADD "LogDbEntryId" bigint;

ALTER TABLE "TaskBoardColumns" ADD "LogDbEntryId" bigint;

ALTER TABLE "TaskAutomationRules" ADD "LogDbEntryId" bigint;

CREATE UNIQUE INDEX "IX_TaskTeams_LogDbEntryId" ON "TaskTeams" ("LogDbEntryId");

CREATE UNIQUE INDEX "IX_TaskItems_LogDbEntryId" ON "TaskItems" ("LogDbEntryId");

CREATE UNIQUE INDEX "IX_TaskBoards_LogDbEntryId" ON "TaskBoards" ("LogDbEntryId");

CREATE UNIQUE INDEX "IX_TaskBoardColumns_LogDbEntryId" ON "TaskBoardColumns" ("LogDbEntryId");

CREATE UNIQUE INDEX "IX_TaskAutomationRules_LogDbEntryId" ON "TaskAutomationRules" ("LogDbEntryId");

ALTER TABLE "TaskAutomationRules" ADD CONSTRAINT "FK_TaskAutomationRules_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id");

ALTER TABLE "TaskBoardColumns" ADD CONSTRAINT "FK_TaskBoardColumns_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id");

ALTER TABLE "TaskBoards" ADD CONSTRAINT "FK_TaskBoards_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id");

ALTER TABLE "TaskItems" ADD CONSTRAINT "FK_TaskItems_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id");

ALTER TABLE "TaskTeams" ADD CONSTRAINT "FK_TaskTeams_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260414193759_MigrateTasksToIAuditedEntity', '10.0.1');

COMMIT;



GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO limousine;

