-- Миграции прода 2026-08-30: три аддитивные, скрипт идемпотентный (EF --idempotent).
-- От 20260820043448_AddUnifiedNotifications до 20260829162009_AddAggregatorPollHeartbeat.
-- Накат: psql -h <host> -p 8432 -U limousine -d daecrm -f 01-migrations.sql

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260822171147_AddFeedbackFields') THEN
    ALTER TABLE "TaskComments" ADD "IsPublic" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260822171147_AddFeedbackFields') THEN
    ALTER TABLE "Notifications" ALTER COLUMN "Module" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260822171147_AddFeedbackFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260822171147_AddFeedbackFields', '10.0.1');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260824191740_AddLoginThrottle') THEN
    ALTER TABLE "UserLogins" ADD "FailedLoginCount" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260824191740_AddLoginThrottle') THEN
    ALTER TABLE "UserLogins" ADD "LockedUntilUtc" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260824191740_AddLoginThrottle') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260824191740_AddLoginThrottle', '10.0.1');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260829162009_AddAggregatorPollHeartbeat') THEN
    CREATE TABLE "AggregatorPollHeartbeats" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "CompanyId" bigint NOT NULL,
        "AggregatorId" integer NOT NULL,
        "LastSuccessUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_AggregatorPollHeartbeats" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260829162009_AddAggregatorPollHeartbeat') THEN
    CREATE UNIQUE INDEX "IX_AggregatorPollHeartbeats_CompanyId_AggregatorId" ON "AggregatorPollHeartbeats" ("CompanyId", "AggregatorId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260829162009_AddAggregatorPollHeartbeat') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260829162009_AddAggregatorPollHeartbeat', '10.0.1');
    END IF;
END $EF$;
COMMIT;



-- Права роли limousine на созданное миграциями. На проде ALTER DEFAULT PRIVILEGES настроен
-- (limousine=arwd на таблицы, rU на сиквенсы), поэтому обычно это no-op — но стоит копейки,
-- а пропущенный GRANT даёт 42501 уже под нагрузкой. Выполнять ПОД postgres, не под limousine.
-- psql -h <host> -p 8432 -U postgres -d daecrm -f 02-grants.sql
\pset pager off

grant select, insert, update, delete on "AggregatorPollHeartbeats" to limousine;
grant usage, select on sequence "AggregatorPollHeartbeats_Id_seq" to limousine;

\echo '== права на новую таблицу (ожидаем limousine=arwd)'
select relname, coalesce(array_to_string(relacl, ','), '(none)') acl
from pg_class c join pg_namespace n on n.oid = c.relnamespace
where n.nspname = 'public' and relname = 'AggregatorPollHeartbeats';
