START TRANSACTION;
ALTER TABLE "Companies" ADD "ExternalServicesEnabled" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Companies" ADD "ExternalServicesScheduleUtcTime" time without time zone;

CREATE TABLE "CompanyExternalServiceConfigs" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" bigint NOT NULL,
    "ExternalServiceKey" text,
    "IsEnabled" boolean NOT NULL,
    "ConfigJson" jsonb,
    CONSTRAINT "PK_CompanyExternalServiceConfigs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CompanyExternalServiceConfigs_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_CompanyExternalServiceConfigs_CompanyId_ExternalServiceKey" ON "CompanyExternalServiceConfigs" ("CompanyId", "ExternalServiceKey");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260521202858_add_ExternalServicesConfigs', '10.0.1');

COMMIT;

START TRANSACTION;
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (107, '', 'Fleet automation / read', 0);
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (108, '', 'Fleet automation / manage', 0);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260522201629_AddFleetAutomationConfig', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "RepairOrders" ADD "LogDbEntryId" bigint;

ALTER TABLE "RepairOperations" ADD "LogDbEntryId" bigint;

ALTER TABLE "Purposes" ADD "LogDbEntryId" bigint;

ALTER TABLE "PosTerminals" ADD "LogDbEntryId" bigint;

ALTER TABLE "OfficePlaces" ADD "LogDbEntryId" bigint;

ALTER TABLE "OfficeOrders" ADD "LogDbEntryId" bigint;

ALTER TABLE "MotivationRules" ADD "LogDbEntryId" bigint;

ALTER TABLE "MotivationPercentGroups" ADD "LogDbEntryId" bigint;

ALTER TABLE "MotivationPercentCarModels" ADD "LogDbEntryId" bigint;

ALTER TABLE "MotivationPercentages" ADD "LogDbEntryId" bigint;

ALTER TABLE "MotivationExpenses" ADD "LogDbEntryId" bigint;

ALTER TABLE "Counterparties" ADD "LogDbEntryId" bigint;

ALTER TABLE "CashBoxes" ADD "LogDbEntryId" bigint;

CREATE INDEX "IX_RepairOrders_LogDbEntryId" ON "RepairOrders" ("LogDbEntryId");

CREATE INDEX "IX_RepairOperations_LogDbEntryId" ON "RepairOperations" ("LogDbEntryId");

CREATE INDEX "IX_Purposes_LogDbEntryId" ON "Purposes" ("LogDbEntryId");

CREATE INDEX "IX_PosTerminals_LogDbEntryId" ON "PosTerminals" ("LogDbEntryId");

CREATE INDEX "IX_OfficePlaces_LogDbEntryId" ON "OfficePlaces" ("LogDbEntryId");

CREATE INDEX "IX_OfficeOrders_LogDbEntryId" ON "OfficeOrders" ("LogDbEntryId");

CREATE INDEX "IX_MotivationRules_LogDbEntryId" ON "MotivationRules" ("LogDbEntryId");

CREATE INDEX "IX_MotivationPercentGroups_LogDbEntryId" ON "MotivationPercentGroups" ("LogDbEntryId");

CREATE INDEX "IX_MotivationPercentCarModels_LogDbEntryId" ON "MotivationPercentCarModels" ("LogDbEntryId");

CREATE INDEX "IX_MotivationPercentages_LogDbEntryId" ON "MotivationPercentages" ("LogDbEntryId");

CREATE INDEX "IX_MotivationExpenses_LogDbEntryId" ON "MotivationExpenses" ("LogDbEntryId");

CREATE INDEX "IX_Counterparties_LogDbEntryId" ON "Counterparties" ("LogDbEntryId");

CREATE INDEX "IX_CashBoxes_LogDbEntryId" ON "CashBoxes" ("LogDbEntryId");

ALTER TABLE "CashBoxes" ADD CONSTRAINT "FK_CashBoxes_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id");

ALTER TABLE "Counterparties" ADD CONSTRAINT "FK_Counterparties_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id");

ALTER TABLE "MotivationExpenses" ADD CONSTRAINT "FK_MotivationExpenses_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id");

ALTER TABLE "MotivationPercentages" ADD CONSTRAINT "FK_MotivationPercentages_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id");

ALTER TABLE "MotivationPercentCarModels" ADD CONSTRAINT "FK_MotivationPercentCarModels_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id");

ALTER TABLE "MotivationPercentGroups" ADD CONSTRAINT "FK_MotivationPercentGroups_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id");

ALTER TABLE "MotivationRules" ADD CONSTRAINT "FK_MotivationRules_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id");

ALTER TABLE "OfficeOrders" ADD CONSTRAINT "FK_OfficeOrders_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id");

ALTER TABLE "OfficePlaces" ADD CONSTRAINT "FK_OfficePlaces_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id");

ALTER TABLE "PosTerminals" ADD CONSTRAINT "FK_PosTerminals_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id");

ALTER TABLE "Purposes" ADD CONSTRAINT "FK_Purposes_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id");

ALTER TABLE "RepairOperations" ADD CONSTRAINT "FK_RepairOperations_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id");

ALTER TABLE "RepairOrders" ADD CONSTRAINT "FK_RepairOrders_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260523170419_add_AuditEntities', '10.0.1');

COMMIT;

