START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925202321_AddIllegalTripSignal') THEN
    ALTER TABLE "CabmanTrips" ADD "SignalAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925202321_AddIllegalTripSignal') THEN
    ALTER TABLE "CabmanTrips" ADD "SignalTelegramMessageId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925202321_AddIllegalTripSignal') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260925202321_AddIllegalTripSignal', '10.0.1');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925211249_AddSharyoTracker') THEN
    CREATE TABLE "SharyoCompanies" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "CompanyId" bigint NOT NULL,
        "BaseUrl" text,
        "Username" text,
        "Password" text,
        "TripSignal" integer NOT NULL,
        "OnlyKnownCars" boolean NOT NULL,
        CONSTRAINT "PK_SharyoCompanies" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SharyoCompanies_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925211249_AddSharyoTracker') THEN
    INSERT INTO "Trackers" ("Id", "Name")
    VALUES (2, 'Sharyo');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925211249_AddSharyoTracker') THEN
    CREATE UNIQUE INDEX "IX_SharyoCompanies_CompanyId" ON "SharyoCompanies" ("CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260925211249_AddSharyoTracker') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260925211249_AddSharyoTracker', '10.0.1');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260926135502_AddIllegalTripOrderFound') THEN
    ALTER TABLE "CabmanTrips" ADD "OrderFound" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260926135502_AddIllegalTripOrderFound') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260926135502_AddIllegalTripOrderFound', '10.0.1');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260926153258_AddIllegalTripOfficeOrder') THEN
    ALTER TABLE "CabmanTrips" ADD "OfficeOrderId" bigint;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260926153258_AddIllegalTripOfficeOrder') THEN
    CREATE INDEX "IX_CabmanTrips_OfficeOrderId" ON "CabmanTrips" ("OfficeOrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260926153258_AddIllegalTripOfficeOrder') THEN
    ALTER TABLE "CabmanTrips" ADD CONSTRAINT "FK_CabmanTrips_OfficeOrders_OfficeOrderId" FOREIGN KEY ("OfficeOrderId") REFERENCES "OfficeOrders" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260926153258_AddIllegalTripOfficeOrder') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260926153258_AddIllegalTripOfficeOrder', '10.0.1');
    END IF;
END $EF$;
COMMIT;

