START TRANSACTION;
DROP INDEX "IX_UserSummaryStatuses_UserId";

DROP INDEX "IX_AggrDriverStatuses_DriverId";

CREATE INDEX "IX_UserSummaryStatuses_UserId_StartTime" ON "UserSummaryStatuses" ("UserId", "StartTime");

CREATE INDEX "IX_AggrDriverStatuses_DriverId_AggregatorId_DateTime" ON "AggrDriverStatuses" ("DriverId", "AggregatorId", "DateTime");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260619180134_AddWorkDiagramQueryIndexes', '10.0.1');

COMMIT;

START TRANSACTION;
DROP INDEX "IX_CarModels_CarBrandId";

ALTER TABLE "CarModels" ADD "NormalizedModel" text;

ALTER TABLE "CarBrands" ADD "NormalizedName" text;

CREATE TABLE "VehicleModelResolutions" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Source" integer NOT NULL,
    "RawBrand" text,
    "RawModel" text,
    "RawCombined" text,
    "NormalizedKey" text,
    "SuggestedCarBrandId" bigint,
    "ResolvedCarModelId" bigint,
    "ResolvedByUserId" bigint,
    "Status" integer NOT NULL,
    "CreatedTime" timestamp with time zone NOT NULL,
    "ModifiedTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_VehicleModelResolutions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_VehicleModelResolutions_CarBrands_SuggestedCarBrandId" FOREIGN KEY ("SuggestedCarBrandId") REFERENCES "CarBrands" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_VehicleModelResolutions_CarModels_ResolvedCarModelId" FOREIGN KEY ("ResolvedCarModelId") REFERENCES "CarModels" ("Id") ON DELETE SET NULL
);

CREATE UNIQUE INDEX "IX_CarModels_CarBrandId_NormalizedModel" ON "CarModels" ("CarBrandId", "NormalizedModel");

CREATE UNIQUE INDEX "IX_CarBrands_NormalizedName" ON "CarBrands" ("NormalizedName");

CREATE INDEX "IX_VehicleModelResolutions_ResolvedCarModelId" ON "VehicleModelResolutions" ("ResolvedCarModelId");

CREATE UNIQUE INDEX "IX_VehicleModelResolutions_Source_NormalizedKey" ON "VehicleModelResolutions" ("Source", "NormalizedKey");

CREATE INDEX "IX_VehicleModelResolutions_SuggestedCarBrandId" ON "VehicleModelResolutions" ("SuggestedCarBrandId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260619190112_AddVehicleModelNormalization', '10.0.1');

COMMIT;

START TRANSACTION;
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (161, '', 'Car dictionary / manage', 0);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260619190903_AddCarDictionaryManageAccess', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "PosTerminalUsages" ADD "Details" text;

ALTER TABLE "PosTerminalUsages" ADD "LogDbEntryId" bigint;

INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (162, '', 'Driver POS terminal / change', 0);

CREATE INDEX "IX_PosTerminalUsages_LogDbEntryId" ON "PosTerminalUsages" ("LogDbEntryId");

ALTER TABLE "PosTerminalUsages" ADD CONSTRAINT "FK_PosTerminalUsages_LogDbEntries_LogDbEntryId" FOREIGN KEY ("LogDbEntryId") REFERENCES "LogDbEntries" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260620151929_AddPosTerminalAssignmentHistory', '10.0.1');

COMMIT;

START TRANSACTION;

                WITH brand_map AS (
                  SELECT "Id", MIN("Id") OVER (
                           PARTITION BY upper(regexp_replace("Name", '[^A-Za-z0-9]', '', 'g'))) AS winner
                  FROM "CarBrands")
                UPDATE "CarModels" m SET "CarBrandId" = bm.winner
                FROM brand_map bm WHERE m."CarBrandId" = bm."Id" AND bm."Id" <> bm.winner;


                WITH brand_map AS (
                  SELECT "Id", MIN("Id") OVER (
                           PARTITION BY upper(regexp_replace("Name", '[^A-Za-z0-9]', '', 'g'))) AS winner
                  FROM "CarBrands")
                UPDATE "VehicleModelResolutions" r SET "SuggestedCarBrandId" = bm.winner
                FROM brand_map bm WHERE r."SuggestedCarBrandId" = bm."Id" AND bm."Id" <> bm.winner;


                WITH brand_map AS (
                  SELECT "Id", MIN("Id") OVER (
                           PARTITION BY upper(regexp_replace("Name", '[^A-Za-z0-9]', '', 'g'))) AS winner
                  FROM "CarBrands")
                DELETE FROM "CarBrands" b USING brand_map bm
                WHERE b."Id" = bm."Id" AND bm."Id" <> bm.winner;


                WITH model_map AS (
                  SELECT "Id", MIN("Id") OVER (
                           PARTITION BY "CarBrandId", upper(regexp_replace("Model", '[^A-Za-z0-9]', '', 'g'))) AS winner
                  FROM "CarModels")
                UPDATE "Cars" c SET "CarModelId" = mm.winner
                FROM model_map mm WHERE c."CarModelId" = mm."Id" AND mm."Id" <> mm.winner;


                WITH model_map AS (
                  SELECT "Id", MIN("Id") OVER (
                           PARTITION BY "CarBrandId", upper(regexp_replace("Model", '[^A-Za-z0-9]', '', 'g'))) AS winner
                  FROM "CarModels")
                DELETE FROM "MotivationPercentCarModels" mp USING model_map mm
                WHERE mp."CarModelId" = mm."Id" AND mm."Id" <> mm.winner
                  AND EXISTS (SELECT 1 FROM "MotivationPercentCarModels" w
                              WHERE w."CarModelId" = mm.winner
                                AND w."MotivationPercentGroupId" = mp."MotivationPercentGroupId");


                WITH model_map AS (
                  SELECT "Id", MIN("Id") OVER (
                           PARTITION BY "CarBrandId", upper(regexp_replace("Model", '[^A-Za-z0-9]', '', 'g'))) AS winner
                  FROM "CarModels")
                UPDATE "MotivationPercentCarModels" mp SET "CarModelId" = mm.winner
                FROM model_map mm WHERE mp."CarModelId" = mm."Id" AND mm."Id" <> mm.winner;


                WITH model_map AS (
                  SELECT "Id", MIN("Id") OVER (
                           PARTITION BY "CarBrandId", upper(regexp_replace("Model", '[^A-Za-z0-9]', '', 'g'))) AS winner
                  FROM "CarModels")
                UPDATE "VehicleModelResolutions" r SET "ResolvedCarModelId" = mm.winner
                FROM model_map mm WHERE r."ResolvedCarModelId" = mm."Id" AND mm."Id" <> mm.winner;


                WITH model_map AS (
                  SELECT "Id", MIN("Id") OVER (
                           PARTITION BY "CarBrandId", upper(regexp_replace("Model", '[^A-Za-z0-9]', '', 'g'))) AS winner
                  FROM "CarModels")
                DELETE FROM "CarModels" m USING model_map mm
                WHERE m."Id" = mm."Id" AND mm."Id" <> mm.winner;


                UPDATE "CarBrands"
                SET "NormalizedName" = upper(regexp_replace("Name", '[^A-Za-z0-9]', '', 'g'))
                WHERE "NormalizedName" IS DISTINCT FROM upper(regexp_replace("Name", '[^A-Za-z0-9]', '', 'g'));


                UPDATE "CarModels"
                SET "NormalizedModel" = upper(regexp_replace("Model", '[^A-Za-z0-9]', '', 'g'))
                WHERE "NormalizedModel" IS DISTINCT FROM upper(regexp_replace("Model", '[^A-Za-z0-9]', '', 'g'));

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260621130946_MergeAndBackfillCarDictionary', '10.0.1');

COMMIT;

START TRANSACTION;
INSERT INTO "AuthAccesses" ("Id", "Description", "Name", "Priority")
VALUES (163, '', 'P&L report / read', 0);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260622115851_AddPnlReadAccess', '10.0.1');

COMMIT;

START TRANSACTION;
ALTER TABLE "CompanyBotConfigs" ADD "ReceivesDriverReports" boolean NOT NULL DEFAULT TRUE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260622195658_AddReceivesDriverReportsToBotConfig', '10.0.1');

COMMIT;

