START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920093302_AddDriverNotificationSettings') THEN
    CREATE TABLE "DriverNotificationSettings" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "CompanyId" bigint NOT NULL,
        "DailySummaryEnabled" boolean NOT NULL,
        "DailySummaryLocalTime" time without time zone NOT NULL,
        "IllegalTripNotifyEnabled" boolean NOT NULL,
        "IllegalTripDelayMinutes" integer NOT NULL,
        "MentionPhones" text[],
        "FallbackManagerPhone" text,
        "CreatedTime" timestamp with time zone NOT NULL,
        "ModifiedTime" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_DriverNotificationSettings" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_DriverNotificationSettings_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920093302_AddDriverNotificationSettings') THEN
    CREATE UNIQUE INDEX "IX_DriverNotificationSettings_CompanyId" ON "DriverNotificationSettings" ("CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920093302_AddDriverNotificationSettings') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260920093302_AddDriverNotificationSettings', '10.0.1');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920093928_AddDriverWhatsappMessages') THEN
    CREATE TABLE "DriverWhatsappMessages" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "CompanyId" bigint NOT NULL,
        "DriverId" bigint NOT NULL,
        "Kind" integer NOT NULL,
        "RefId" bigint,
        "LocalDate" date NOT NULL,
        "Status" integer NOT NULL,
        "ChatId" text,
        "Body" text,
        "Error" text,
        "SentAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_DriverWhatsappMessages" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_DriverWhatsappMessages_Companies_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES "Companies" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920093928_AddDriverWhatsappMessages') THEN
    CREATE INDEX "IX_DriverWhatsappMessages_CompanyId" ON "DriverWhatsappMessages" ("CompanyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920093928_AddDriverWhatsappMessages') THEN
    CREATE UNIQUE INDEX "IX_DriverWhatsappMessages_Kind_CompanyId_DriverId_LocalDate" ON "DriverWhatsappMessages" ("Kind", "CompanyId", "DriverId", "LocalDate") WHERE "Kind" = 1 AND "Status" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920093928_AddDriverWhatsappMessages') THEN
    CREATE UNIQUE INDEX "IX_DriverWhatsappMessages_Kind_RefId" ON "DriverWhatsappMessages" ("Kind", "RefId") WHERE "Kind" = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260920093928_AddDriverWhatsappMessages') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260920093928_AddDriverWhatsappMessages', '10.0.1');
    END IF;
END $EF$;
COMMIT;

